"use client";
import { usePathname } from "next/navigation";
import Link from "next/link";
import { Activity, Bell, ChartNoAxesCombined, ChevronDown, Home, Menu, Settings, ShoppingBasket, Wallet, X } from "lucide-react";
import { useEffect, useState } from "react";
import { PwaRegistration } from "@/components/pwa-registration";
import {useHouseholdState} from "@/lib/use-household-state";
import {getCriticalMarketAlerts} from "@/lib/market-alerts";

const nav=[
  {title:"ÜBERSICHT",items:[{label:"Dashboard",href:"/",icon:Home}]},
  {title:"WOHNUNG",items:[{label:"Haushaltskonto",href:"/finanzen",icon:Wallet},{label:"Einkaufsliste",href:"/einkauf",icon:ShoppingBasket}]},
  {title:"MARKT",items:[{label:"Marktanalyse",href:"/berichte",icon:ChartNoAxesCombined}]},
];
export function AppShell({children}:{children:React.ReactNode}){
  const path=usePathname(); const [open,setOpen]=useState(false); const [adminUrl,setAdminUrl]=useState("");const [today,setToday]=useState("");const [notifications,setNotifications]=useState<{title:string;detail:string;href:string}[]>([]);const [showNotifications,setShowNotifications]=useState(false);const [preferences,,preferencesReady]=useHouseholdState<{compactMode?:boolean;reducedMotion?:boolean}>("preferences",{compactMode:true,reducedMotion:false});
  async function refreshNotifications(){let next:{title:string;detail:string;href:string}[]=[];let marketEnabled=true;try{const response=await fetch("/api/state",{cache:"no-store"});if(response.ok){const state=await response.json() as Record<string,any>;const prefs=state.preferences||{};marketEnabled=prefs.marketCriticalNotifications!==false;const items=Array.isArray(state.shoppingItems)?state.shoppingItems:[];const done=Array.isArray(state.shoppingDone)?state.shoppingDone:[];const openItems=items.filter((item:any)=>!done.includes(item.id));if(prefs.shoppingNotifications!==false&&openItems.length)next.push({title:"Einkaufsliste",detail:`${openItems.length} Artikel noch offen`,href:"/einkauf"});const balance=Number(state.accountBalance);const threshold=Number(prefs.lowBalanceLimit??100);if(prefs.lowBalanceNotifications!==false&&Number.isFinite(balance)&&balance<=threshold)next.push({title:"Wohnungskonto",detail:`Kontostand ${new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(balance)} · Grenzwert ${threshold} €`,href:"/finanzen"});if(prefs.fixedCostNotifications!==false&&Array.isArray(state.fixedCosts)){const todayDate=new Date();const inSeven=new Date(todayDate);inSeven.setDate(inSeven.getDate()+7);const due=state.fixedCosts.filter((cost:any)=>{if(!cost.active)return false;const day=Number(String(cost.due).match(/\d{1,2}/)?.[0]);if(!day||day>31)return false;const nextDate=new Date(todayDate.getFullYear(),todayDate.getMonth(),day);if(nextDate<new Date(todayDate.getFullYear(),todayDate.getMonth(),todayDate.getDate()))nextDate.setMonth(nextDate.getMonth()+1);return nextDate<=inSeven});if(due.length)next.push({title:"Fixkosten bald fällig",detail:due.map((cost:any)=>cost.name).join(", "),href:"/finanzen?tab=Fixkosten"})}}}catch{}setNotifications(next);if(!marketEnabled)return;try{const marketResponse=await fetch("/api/market",{cache:"no-store"});if(!marketResponse.ok)return;const market=await marketResponse.json() as {news?:Parameters<typeof getCriticalMarketAlerts>[0];assets?:Parameters<typeof getCriticalMarketAlerts>[1];stocks?:Parameters<typeof getCriticalMarketAlerts>[2]};const alerts=getCriticalMarketAlerts(market.news||[],market.assets||[],market.stocks||[]).map(alert=>({title:alert.title,detail:alert.detail,href:alert.href}));setNotifications(current=>[...current.filter(item=>!item.title.startsWith("Kritische ")&&!item.title.startsWith("Starker Kursrückgang")),...alerts])}catch{}}
  useEffect(()=>{fetch("/api/config").then(r=>r.json()).then(v=>setAdminUrl(v.adminUrl??"")).catch(()=>{});setToday(new Intl.DateTimeFormat("de-AT",{weekday:"short",day:"2-digit",month:"long",timeZone:"Europe/Vienna"}).format(new Date()));void refreshNotifications();},[]);
  useEffect(()=>{if(!preferencesReady)return;document.documentElement.dataset.density=preferences.compactMode===false?"comfortable":"compact";document.documentElement.dataset.motion=preferences.reducedMotion?"reduced":"normal"},[preferencesReady,preferences.compactMode,preferences.reducedMotion]);
  return <div className="app-layout"><PwaRegistration/>
    <aside className={`sidebar ${open?"open":""}`}><Link href="/" className="brand"><span className="brand-mark"><Home size={17}/></span><span>WG Cockpit<small>Unser Zuhause, im Blick.</small></span><button className="mobile-close" onClick={()=>setOpen(false)}><X size={18}/></button></Link>
      <nav>{nav.map(group=><div className="nav-group" key={group.title}><div className="nav-label">{group.title}</div>{group.items.map(item=>{const active=path===item.href||(item.href==="/berichte"&&path==="/berichte");const Icon=item.icon;return <Link key={item.label} onClick={()=>setOpen(false)} className={`nav-item ${active?"active":""}`} href={item.href}><Icon size={17}/><span>{item.label}</span>{active&&<span className="nav-active-dot"/>}</Link>})}</div>)}</nav>
      <div className="sidebar-spacer"/><a className="admin-link" href={adminUrl||"/admin"}><span className="admin-icon"><Activity size={16}/></span><span><b>Admin Cockpit</b><small>Separates Add-on</small></span><span className="external-arrow">↗</span></a><Link className="nav-item settings-link" href="/einstellungen"><Settings size={17}/><span>Einstellungen</span></Link>
      <div className="profile"><div className="avatar">M</div><div><b>Marcel</b><small>WG Mitglied</small></div><button aria-label="Profiloptionen"><ChevronDown size={15}/></button></div>
    </aside>
    {open&&<button className="sidebar-scrim" aria-label="Menü schließen" onClick={()=>setOpen(false)}/>}
    <main className="main-area"><header className="topbar"><button className="mobile-menu" aria-label="Menü öffnen" onClick={()=>setOpen(true)}><Menu size={20}/></button><div className="crumb"><span>WG Cockpit</span><span>/</span><b>{path==="/"?"Dashboard":path.split("/")[1]?.replace("-"," ")}</b></div><div className="topbar-actions"><span className="today-label">{today}</span><div className="notification-wrap"><button className="icon-button" aria-label="Benachrichtigungen" aria-expanded={showNotifications} onClick={()=>{setShowNotifications(v=>!v);void refreshNotifications()}}><Bell size={17}/>{notifications.length>0&&<i/>}</button>{showNotifications&&<div className="notification-popover" role="dialog" aria-label="Benachrichtigungen"><div className="notification-head"><b>Benachrichtigungen</b><button onClick={()=>setShowNotifications(false)} aria-label="Schließen">×</button></div>{notifications.length?notifications.map((n,i)=><Link onClick={()=>setShowNotifications(false)} href={n.href} className="notification-item" key={i}><b>{n.title}</b><small>{n.detail}</small><span>Öffnen →</span></Link>):<div className="notification-empty"><b>Alles erledigt</b><small>Keine aktiven Hinweise. Einstellungen der Glocke kannst du anpassen.</small><Link href="/einstellungen" onClick={()=>setShowNotifications(false)}>Einstellungen öffnen</Link></div>}</div>}</div><div className="top-avatar">M</div></div></header><div className="page-container">{children}</div><footer className="app-footer"><span>WG Cockpit</span><span>Einfach zusammen wohnen.</span></footer></main>
  </div>
}
