name: Admin Cockpit
slug: admin_cockpit
description: Separates Monitoring-Cockpit für Server, Docker, Home Assistant, NAS und Netzwerk.
version: 0.1.18
startup: application
boot: auto
init: false
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 8099
panel_icon: mdi:server-security
panel_title: Admin Cockpit
hassio_api: true
hassio_role: default
homeassistant_api: true
map:
  - data:rw
options:
  portainer_url: ""
  portainer_api_key: ""
schema:
  portainer_url: str
  portainer_api_key: password
