"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {Database,ExternalLink,RefreshCw,X,Languages} from "lucide-react";
import {Panel,Pill,SectionTitle} from "@/components/ui";
import {getCriticalMarketAlerts} from "@/lib/market-alerts";

type Category="KI"|"Quantum"|"Krypto";
type News={id:string;title:string;summary:string;url:string;source:string;date:string;category:Category};
type Asset={id:string;name:string;symbol:string;price:number;change24h:number;change7d:number;marketCap:number};
type StockQuote={symbol:string;price:number;currency:string;changePercent:number;updatedAt:string};
type SourceStatus={name:string;status:"online"|"unavailable";detail:string};
type Data={news:News[];assets:Asset[];stocks:StockQuote[];fxRate:number|null;updatedAt:string;sources:string[];sourceStatus?:SourceStatus[];warnings:string[]};
const MARKET_CACHE_KEY="wg-market-cache-v1";
const tabs:Category[]=["KI","Quantum","Krypto"];
const fmt=(value:number,digits=2)=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR",maximumFractionDigits:digits}).format(value);
const percent=(n:number)=>`${n>0?"+":""}${n.toLocaleString("de-AT",{maximumFractionDigits:1})} %`;
export default function Berichte(){
 const [tab,setTab]=useState<Category>("KI");
 const [range,setRange]=useState("24 Stunden");
 const [data,setData]=useState<Data>({news:[],assets:[],stocks:[],fxRate:null,updatedAt:"",sources:[],sourceStatus:[],warnings:[]});
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState("");
 const [showSources,setShowSources]=useState(false);
 const [sourcePosition,setSourcePosition]=useState({top:64,right:12});const sourceButtonRef=useRef<HTMLButtonElement>(null);
 function updateSourcePosition(){const rect=sourceButtonRef.current?.getBoundingClientRect();if(!rect)return;const height=Math.min(window.innerHeight*.7,560);let top=rect.bottom+8;if(top+height>window.innerHeight-12)top=Math.max(12,rect.top-height-8);setSourcePosition({top,right:Math.max(12,window.innerWidth-rect.right)})}
 function toggleSources(){if(showSources){setShowSources(false);return}updateSourcePosition();setShowSources(true)}
 const refresh=useCallback(async(force=false)=>{setLoading(true);setError("");try{const response=await fetch(`/api/market${force?"?refresh=1":""}`,{cache:"no-store"});const next=await response.json() as Data;setData(next);try{if(next.news.length||next.assets.length)localStorage.setItem(MARKET_CACHE_KEY,JSON.stringify(next))}catch{}setError(next.warnings?.join(" ")||"")}catch{setError("Marktdaten momentan nicht erreichbar.")}finally{setLoading(false)}},[]);
 useEffect(()=>{const query=new URLSearchParams(window.location.search);const requested=query.get("tab");if(requested&&tabs.includes(requested as Category))setTab(requested as Category);try{const cached=localStorage.getItem(MARKET_CACHE_KEY);if(cached){const parsed=JSON.parse(cached) as Data;if(Array.isArray(parsed.news)&&Array.isArray(parsed.assets))setData({...parsed,stocks:Array.isArray(parsed.stocks)?parsed.stocks:[]})}}catch{}void refresh()},[refresh]);
 useEffect(()=>{if(!showSources)return;const update=()=>updateSourcePosition();const key=(event:KeyboardEvent)=>{if(event.key==="Escape")setShowSources(false)};window.addEventListener("resize",update);window.addEventListener("scroll",update,true);window.addEventListener("keydown",key);return()=>{window.removeEventListener("resize",update);window.removeEventListener("scroll",update,true);window.removeEventListener("keydown",key)}},[showSources]);
 const visible=useMemo(()=>data.news.filter(item=>item.category===tab&&(range==="Alle Zeiträume"||!item.date||Date.now()-Date.parse(item.date)<(range==="24 Stunden"?86400000:7*86400000))),[data.news,tab,range]);
 const relevantError=tab==="KI"||tab==="Quantum"?error.split("Krypto-Kurse gerade nicht erreichbar")[0].trim():error;
 const criticalCategories=new Set(getCriticalMarketAlerts(data.news,data.assets,data.stocks).map(alert=>alert.category));
 const notable=data.assets.filter(asset=>Math.abs(asset.change24h)>=3).length;
 return <div className="page-stack market-page">
  <div className="market-page-heading"><h1>Marktanalyse</h1><button className="button button-primary" onClick={()=>void refresh(true)} disabled={loading}><RefreshCw size={15} className={loading?"spin-icon":""}/>{loading?"Lade …":"Aktualisieren"}</button></div>
  <div className="market-snapshot"><b>Snapshot: {data.updatedAt?new Date(data.updatedAt).toLocaleString("de-AT"):"wird geladen"}</b></div>
  <div className="market-tabbar"><div className="market-tabs" role="tablist" aria-label="Marktanalyse Bereiche">{tabs.map(t=>{const critical=criticalCategories.has(t);return <button key={t} role="tab" aria-selected={tab===t} aria-label={critical?`${t}, kritische Meldung vorhanden`:t} className={`market-tab ${tab===t?"selected":""}`} onClick={()=>setTab(t)}>{t}{critical&&<i className="market-critical-dot" title="Kritische Meldung vorhanden" aria-hidden="true"/>}</button>})}</div><div className="source-control"><button ref={sourceButtonRef} className="source-trigger" aria-haspopup="dialog" aria-expanded={showSources} onClick={toggleSources}><Database size={14}/> Datenquellen</button></div></div>
  {showSources&&createPortal(<div className="source-popover-overlay" onMouseDown={()=>setShowSources(false)}><div className="source-popover source-popover-portal" style={{top:sourcePosition.top,right:sourcePosition.right}} role="dialog" aria-modal="true" aria-label="Datenquellen und Status" onMouseDown={event=>event.stopPropagation()}><div className="source-popover-head"><div><b>Datenquellen</b><small>Status des letzten Abrufs</small></div><button onClick={()=>setShowSources(false)} aria-label="Schließen"><X size={16}/></button></div>{(data.sourceStatus||[]).map(source=><div className="source-status-row" key={source.name}><i className={source.status}/><span><b>{source.name}</b><small>{source.detail}</small></span><Pill tone={source.status==="online"?"green":"red"}>{source.status==="online"?"Online":"Offline"}</Pill></div>)}{!data.sourceStatus?.length&&<p className="quiet-note">Quellenstatus wird mit dem nächsten Abruf geladen.</p>}<p className="source-popover-foot">Keine kostenpflichtigen Schlüssel oder LLM-Abfragen.</p></div></div>,document.body)}
  {relevantError&&<div className="market-notice" role="status">{relevantError} Die letzte erfolgreiche Anzeige bleibt verwendbar.</div>}
  {tab==="Quantum"?<QuantumReport items={visible} stocks={data.stocks} loading={loading} range={range} setRange={setRange}/>:tab==="Krypto"?<>
   <div className="stats-grid two"><MarketStat name="Live-Kurse" value={String(data.assets.length)} description="Kryptowährungen in Euro" tone="orange"/><MarketStat name="Starke Bewegungen" value={String(notable)} description="Mindestens ±3 % in 24 Stunden" tone="green"/></div>
   <div className="content-grid reports-grid"><Panel><div className="panel-heading"><SectionTitle title="Krypto-Meldungen" description={`${visible.length} aktuelle Meldungen`}/><PeriodSelect value={range} onChange={setRange}/></div><NewsList items={visible} loading={loading}/></Panel><Panel><div className="panel-heading"><SectionTitle title="Kryptowährungen" description="CoinLore-Kurse, umgerechnet mit dem Frankfurter USD/EUR-Referenzkurs"/></div>{loading&&!data.assets.length?<div className="loading-state">Kurse werden geladen …</div>:data.assets.length?data.assets.map(asset=><MarketAssetRow key={asset.id} asset={asset}/>):<p className="quiet-note">Kurse vorübergehend nicht verfügbar.</p>}{data.assets.length>0&&<small className="market-data-foot">Marktkapitalisierung: {fmt(data.assets.reduce((sum,asset)=>sum+asset.marketCap,0),0)} · keine Anlageempfehlung</small>}</Panel></div>
  </>:tab==="KI"?<><AIModelDigest/><Panel><div className="panel-heading"><SectionTitle title="KI-Meldungen" description={`${visible.length} relevante Meldungen · direkt zur Originalquelle`}/><PeriodSelect value={range} onChange={setRange}/></div><NewsList items={visible} loading={loading}/></Panel></>:<Panel><div className="panel-heading"><SectionTitle title={`${tab} Meldungen`} description={`${visible.length} relevante Meldungen · direkt zur Originalquelle`}/><PeriodSelect value={range} onChange={setRange}/></div><NewsList items={visible} loading={loading}/></Panel>}
 </div>;
}
function PeriodSelect({value,onChange}:{value:string;onChange:(value:string)=>void}){return <select aria-label="Zeitraum" value={value} onChange={event=>onChange(event.target.value)}><option>Alle Zeiträume</option><option>24 Stunden</option><option>7 Tage</option></select>}
function NewsList({items,loading}:{items:News[];loading:boolean}){
 if(loading&&!items.length)return <div className="loading-state">Quellen werden abgefragt …</div>;
 if(!items.length)return <p className="quiet-note">Für diese Auswahl gibt es gerade keine Meldungen.</p>;
 return <div className="article-list">{items.map(item=><article className="article-row live-article" key={item.id}><div className={`article-icon ${item.category.toLowerCase()}`}>{item.category==="KI"?"KI":item.category==="Krypto"?"₿":"Q"}</div><div className="article-content"><ArticleText item={item}/><div className="article-meta"><span>{item.source}{item.date?" · "+new Date(item.date).toLocaleString("de-AT",{dateStyle:"short",timeStyle:"short"}):""}</span></div></div><a className="button button-quiet details-button" href={item.url} target="_blank" rel="noreferrer">Original <ExternalLink size={14}/></a></article>)}</div>;
}
type TranslationAPI={availability:(options:{sourceLanguage:string;targetLanguage:string})=>Promise<string>;create:(options:{sourceLanguage:string;targetLanguage:string})=>Promise<{translate:(text:string)=>Promise<string>;destroy?:()=>void}>};
type DetectorAPI={create:()=>Promise<{detect:(text:string)=>Promise<{detectedLanguage:string;confidence:number}[]>;destroy?:()=>void}>};
function ArticleText({item}:{item:News}){const [text,setText]=useState("");const [original,setOriginal]=useState(true);const [busy,setBusy]=useState(false);const [note,setNote]=useState("");const translate=async()=>{if(text){setOriginal(value=>!value);return}const w=window as typeof window&{Translator?:TranslationAPI;LanguageDetector?:DetectorAPI};if(!w.Translator){setNote("Die lokale Übersetzung wird von diesem Browser nicht unterstützt.");return}setBusy(true);setNote("");let source="en";try{if(w.LanguageDetector){const detector=await w.LanguageDetector.create();const detected=await detector.detect(`${item.title}. ${item.summary}`);detector.destroy?.();if(detected[0]?.confidence>.35)source=detected[0].detectedLanguage}if(source==="de"){setText(`${item.title}\n${item.summary}`);setOriginal(false);return}const available=await w.Translator.availability({sourceLanguage:source,targetLanguage:"de"});if(available==="unavailable")throw new Error("Für diese Sprache ist kein lokales Sprachmodell verfügbar.");const translator=await w.Translator.create({sourceLanguage:source,targetLanguage:"de"});const translated=await translator.translate(`${item.title}\n${item.summary}`);translator.destroy?.();setText(translated);setOriginal(false)}catch(error){setNote(error instanceof Error?error.message:"Übersetzung nicht verfügbar.")}finally{setBusy(false)}};const visibleText=!original&&text?text:`${item.title}${item.summary?`\n${item.summary}`:""}`;const [visibleTitle,...summaryParts]=visibleText.split("\n");return <><div className="article-title"><b>{visibleTitle}</b></div>{summaryParts.join(" ")&&<p>{summaryParts.join(" ")}</p>}<div className="article-translation"><button type="button" onClick={()=>void translate()} disabled={busy}><Languages size={12}/>{busy?"Übersetze …":text?original?"Deutsch":"Originaltext":"Deutsch"}</button>{note&&<small role="status">{note}</small>}</div></>}
function MarketStat({name,value,description,tone}:{name:string;value:string;description:string;tone:string}){return <Panel className="market-stat"><span className={`market-stat-icon ${tone}`}>{tone==="orange"?"₿":"↗"}</span><small>{name}</small><b>{value}</b><span>{description}</span></Panel>}
const modelProviders=[
 {name:"OpenAI",source:"https://developers.openai.com/api/docs/pricing",models:[{name:"GPT-6 Luna",price:"$0.05 / $0.25",tag:"Günstig"},{name:"GPT-6.1 Sol",price:"$1 / $5",tag:"Allround"},{name:"GPT-6 Astra",price:"$5 / $25",tag:"Stärkstes"}]},
 {name:"Anthropic",source:"https://www.anthropic.com/pricing",models:[{name:"Claude Haiku 4.5",price:"$1 / $5",tag:"Günstig"},{name:"Claude Sonnet 5",price:"$2 / $10",tag:"Allround"},{name:"Claude Opus 4.8",price:"$5 / $25",tag:"Stärkstes"}]},
 {name:"Rest · Google & China",source:"https://ai.google.dev/gemini-api/docs/pricing",models:[{name:"Gemini 3.1 Flash-Lite",price:"$0.25 / $1.50",tag:"Google · Günstig"},{name:"Gemini 3.6 Flash",price:"$0.75 / $3.75",tag:"Google · Allround"},{name:"Gemini 3.1 Pro",price:"$2.70 / $16.20",tag:"Google · Stark"},{name:"DeepSeek V4.1 Flash",price:"$0.30 / $1.20",tag:"China · günstig"},{name:"DeepSeek V4 Pro",price:"$1.32 / $3.96",tag:"China · stark"}]}
];
function AIModelDigest(){const [active,setActive]=useState(0);const touchStart=useRef<{x:number;y:number}|null>(null);const change=(by:number)=>setActive(index=>(index+by+modelProviders.length)%modelProviders.length);return <Panel className="ai-model-panel"><div className="panel-heading"><SectionTitle title="KI-Modelle im Vergleich" description="Aktuelle günstige und leistungsstarke Modelle; alle drei Anbietergruppen gleichzeitig sichtbar."/></div><div className="ai-provider-grid" onTouchStart={event=>{const touch=event.touches[0];touchStart.current={x:touch.clientX,y:touch.clientY}}} onTouchEnd={event=>{if(!touchStart.current)return;const touch=event.changedTouches[0];const dx=touch.clientX-touchStart.current.x;const dy=touch.clientY-touchStart.current.y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.3)change(dx<0?1:-1);touchStart.current=null}}>{modelProviders.map((provider,index)=><section className={`ai-provider-card ${index===active?"mobile-current":""}`} key={provider.name}><span className="ai-provider-pill">{provider.name}</span><div className="ai-model-list">{provider.models.map(model=><div className="ai-model-line" key={model.name}><span><b>{model.name}</b><small>{model.tag}</small></span><strong>{model.price}</strong></div>)}</div></section>)}</div><div className="ai-provider-controls" aria-label="KI-Anbieter wechseln"><button onClick={()=>change(-1)} aria-label="Vorheriger Anbieter">‹</button><span>{active+1} / {modelProviders.length} · wischen zum Wechseln</span><button onClick={()=>change(1)} aria-label="Nächster Anbieter">›</button></div><p className="model-caveat">Ungefähre Standardpreise vor Rabatten und Cache; Google-/DeepSeek-Preise können je Tarif abweichen.</p></Panel>}
const coinPages:Record<string,string>={BTC:"bitcoin",ETH:"ethereum",SOL:"solana",BNB:"binancecoin",XRP:"ripple",ADA:"cardano",DOGE:"dogecoin",AVAX:"avalanche-2"};
function coinUrl(symbol:string){return `https://www.coingecko.com/en/coins/${coinPages[symbol]||symbol.toLowerCase()}`}
type HistoryPoint={time:number;price:number};
function useSmallScreen(){const [small,setSmall]=useState(false);useEffect(()=>{const query=window.matchMedia("(max-width: 760px)");const update=()=>setSmall(query.matches);update();query.addEventListener?.("change",update);return()=>query.removeEventListener?.("change",update)},[]);return small}
function useChartLock(active:boolean){useEffect(()=>{if(!active)return;const bodyOverflow=document.body.style.overflow;const main=document.querySelector<HTMLElement>(".main-area");const mainOverflow=main?.style.overflow;document.body.style.overflow="hidden";if(main)main.style.overflow="hidden";return()=>{document.body.style.overflow=bodyOverflow;if(main)main.style.overflow=mainOverflow||""}},[active])}
function MobileChart({children,onClose,label}:{children:React.ReactNode;onClose:()=>void;label:string}){return <div className="mobile-chart-scrim" onClick={onClose}><div className="mobile-chart-dialog" role="dialog" aria-modal="true" aria-label={label} onClick={event=>event.stopPropagation()}>{children}</div></div>}
function MarketAssetRow({asset}:{asset:Asset}){
 const [open,setOpen]=useState(false);const [points,setPoints]=useState<HistoryPoint[]>([]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const small=useSmallScreen();useChartLock(open&&small);
 useEffect(()=>{if(!open||points.length)return;let alive=true;setBusy(true);fetch("/api/market/history?symbol="+asset.symbol).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"Diagramm nicht verfügbar.");if(alive)setPoints(data.points||[])}).catch(error=>{if(alive)setMessage(error instanceof Error?error.message:"Verlauf nicht verfügbar.")}).finally(()=>{if(alive)setBusy(false)});return()=>{alive=false}},[open,asset.symbol,points.length]);
 const prices=points.map(point=>point.price);const low=Math.min(...prices);const high=Math.max(...prices);const coords=prices.map((price,index)=>(prices.length<2?0:index/(prices.length-1)*100)+","+(prices.length<2?50:42-((price-low)/(high-low||1))*34)).join(" ");
 const chart=<div className="coin-history-popover"><div className="coin-history-head"><div><b>{asset.name}</b><small>Letzte 30 Tage · EUR</small></div><button onClick={()=>setOpen(false)} aria-label="Diagramm schließen"><X size={15}/></button></div>{busy?<div className="coin-history-loading">Monatsverlauf wird geladen …</div>:points.length>1?<><svg viewBox="0 0 100 50" preserveAspectRatio="none" role="img" aria-label={asset.name+" Kursverlauf der letzten 30 Tage"}><polyline points={coords} fill="none" stroke={asset.change24h>=0?"#238667":"#c85f56"} strokeWidth="1.8" vectorEffect="non-scaling-stroke"/></svg><div className="coin-history-scale"><span>{fmt(low,asset.price<1?5:2)}</span><b>{percent(((prices.at(-1)!-prices[0])/prices[0])*100)} · 30 Tage</b><span>{fmt(high,asset.price<1?5:2)}</span></div></>:<p className="coin-history-loading">{message||"Monatsverlauf gerade nicht verfügbar."}</p>}</div>;
 const close=()=>setOpen(false);
 return <div className="market-asset" onMouseLeave={()=>{if(!small)setOpen(false)}}><span className="coin-icon">{asset.symbol==="BTC"?"₿":asset.symbol==="ETH"?"♦":asset.symbol==="SOL"?"◉":asset.symbol==="BNB"?"🟡":"◈"}</span><div className="market-asset-name"><a href={coinUrl(asset.symbol)} target="_blank" rel="noreferrer" title={"Live-Kurs von "+asset.name+" öffnen"}>{asset.name}<ExternalLink size={11}/></a><small>{asset.symbol}</small></div><strong>{fmt(asset.price,asset.price<1?5:2)}</strong><button className={"market-change "+(asset.change24h>=0?"positive":"negative")} aria-label={asset.name+": Monatsdiagramm öffnen"} aria-expanded={open} onMouseEnter={()=>{if(!small)setOpen(true)}} onMouseLeave={event=>{if(!small&&!event.currentTarget.parentElement?.contains(event.relatedTarget as Node|null))setOpen(false)}} onFocus={()=>{if(!small)setOpen(true)}} onBlur={event=>{if(!small&&!event.currentTarget.parentElement?.contains(event.relatedTarget as Node|null))setOpen(false)}} onClick={()=>setOpen(value=>!value)}>{percent(asset.change24h)}</button>{open&&!small&&chart}{open&&small&&createPortal(<MobileChart onClose={close} label={asset.name+" Kursverlauf der letzten 30 Tage"}>{chart}</MobileChart>,document.body)}</div>
}
const quantumCompanies=[
 {name:"IonQ",symbol:"IONQ",matches:/\bIONQ\b|IonQ/i,focus:"Umsatzentwicklung, Kundenaufträge und Umsetzung der veröffentlichten Unternehmensprognose."},
 {name:"D-Wave Quantum",symbol:"QBTS",matches:/\bQBTS\b|D[- ]Wave/i,focus:"Umwandlung gemeldeter Bookings in tatsächliche Umsätze und kommerzielle Nutzung."},
 {name:"Rigetti Computing",symbol:"RGTI",matches:/\bRGTI\b|Rigetti/i,focus:"Kommerzielle Skalierung, verfügbare Liquidität und Fortschritt der Hardware-Roadmap."},
];
function QuantumReport({items,stocks,loading,range,setRange}:{items:News[];stocks:StockQuote[];loading:boolean;range:string;setRange:(value:string)=>void}){
 const [activeCompany,setActiveCompany]=useState(0);const touchStart=useRef<{x:number;y:number}|null>(null);
 const mapped=quantumCompanies.map(company=>({...company,items:items.filter(item=>company.matches.test(`${item.title} ${item.summary}`)).slice(0,3)}));
 const changeCompany=(direction:number)=>setActiveCompany(index=>(index+direction+quantumCompanies.length)%quantumCompanies.length);
 const mappedIds=new Set(mapped.flatMap(company=>company.items.map(item=>item.id)));
 const sectorItems=items.filter(item=>!mappedIds.has(item.id)).slice(0,6);
 return <div className="quantum-report">
  <div className="quantum-report-heading"><h2>Quantum-Aktien</h2><PeriodSelect value={range} onChange={setRange}/></div>
  <div className="quantum-company-grid" onTouchStart={event=>{const touch=event.touches[0];touchStart.current={x:touch.clientX,y:touch.clientY}}} onTouchEnd={event=>{if(!touchStart.current)return;const touch=event.changedTouches[0];const dx=touch.clientX-touchStart.current.x;const dy=touch.clientY-touchStart.current.y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.3)changeCompany(dx<0?1:-1);touchStart.current=null}}>{mapped.map((company,index)=>{const quote=stocks.find(stock=>stock.symbol===company.symbol);return <Panel className={`quantum-company-card ${index===activeCompany?"mobile-current":""}`} key={company.symbol}><div className="quantum-company-heading"><div className="quantum-company-title"><div><b>{company.name}</b><span>{company.symbol}</span></div><QuantumStockPrice quote={quote} loading={loading}/></div><Pill tone={company.items.length?"green":"neutral"}>{company.items.length?`${company.items.length} Meldungen`:"Keine Meldung"}</Pill></div>{company.items.length?<ul className="quantum-company-news">{company.items.map(item=><li key={item.id}><span className="quantum-point"/><a href={item.url} target="_blank" rel="noreferrer"><b>{item.title}</b><small>{item.source}{item.date?` · ${new Date(item.date).toLocaleDateString("de-AT")}`:""}</small></a></li>)}</ul>:<p className="quiet-note">{loading?"Meldungen werden geladen …":"Keine passende aktuelle Meldung im gewählten Zeitraum."}</p>}</Panel>})}</div><div className="quantum-company-controls" aria-label="Quantum-Aktien wechseln"><button onClick={()=>changeCompany(-1)} aria-label="Vorherige Aktie">‹</button><span>{activeCompany+1} / {quantumCompanies.length} · wischen zum Wechseln</span><button onClick={()=>changeCompany(1)} aria-label="Nächste Aktie">›</button></div>
  <Panel><div className="panel-heading"><SectionTitle title="Weitere Quantum-Meldungen"/><PeriodSelect value={range} onChange={setRange}/></div><NewsList items={sectorItems} loading={loading}/></Panel>
 </div>;
}
function QuantumStockPrice({quote,loading}:{quote?:StockQuote;loading:boolean}){
 const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [points,setPoints]=useState<HistoryPoint[]>([]);const [error,setError]=useState("");const small=useSmallScreen();useChartLock(open&&small);
 useEffect(()=>{if(!open||points.length)return;let alive=true;setBusy(true);fetch("/api/market/stock-history?symbol="+(quote?.symbol||""),{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||"Kursverlauf nicht verfügbar.");if(alive)setPoints(data.points||[])}).catch(reason=>{if(alive)setError(reason instanceof Error?reason.message:"Kursverlauf nicht verfügbar.")}).finally(()=>{if(alive)setBusy(false)});return()=>{alive=false}},[open,points.length,quote?.symbol]);
 const prices=points.map(point=>point.price);const low=Math.min(...prices);const high=Math.max(...prices);const coords=prices.map((price,index)=>(prices.length<2?0:index/(prices.length-1)*100)+","+(prices.length<2?50:42-((price-low)/(high-low||1))*34)).join(" ");const amount=quote?new Intl.NumberFormat("en-US",{style:"currency",currency:quote.currency,maximumFractionDigits:2}).format(quote.price):loading?"Lädt …":"—";
 const chart=<span className="quantum-stock-popover"><span className="quantum-stock-popover-head"><b>{(quote?.symbol||"Aktienkurs")+" · letzte 30 Tage"}</b><button onClick={()=>setOpen(false)} aria-label="Diagramm schließen">×</button></span>{busy?<span className="coin-history-loading">Kursverlauf wird geladen …</span>:prices.length>1?<><svg viewBox="0 0 100 50" preserveAspectRatio="none" role="img" aria-label="Aktienkurs der letzten 30 Tage"><polyline points={coords} fill="none" stroke={prices.at(-1)!>=prices[0]?"#238667":"#c85f56"} strokeWidth="1.8" vectorEffect="non-scaling-stroke"/></svg><span className="coin-history-scale"><span>{amountForCurrency(low,quote?.currency)}</span><b>30 Tage</b><span>{amountForCurrency(high,quote?.currency)}</span></span></>:<span className="coin-history-loading">{error||"Kursverlauf nicht verfügbar."}</span>}</span>;
 const close=()=>setOpen(false);
 return <span className="quantum-stock-price-wrap" onMouseEnter={()=>{if(!small)setOpen(true)}} onMouseLeave={()=>{if(!small)setOpen(false)}}><button className="quantum-stock-price" aria-expanded={open} onClick={()=>small?setOpen(value=>!value):setOpen(true)}>{amount}</button>{open&&!small&&chart}{open&&small&&createPortal(<MobileChart onClose={close} label={(quote?.symbol||"Aktie")+" Kursverlauf der letzten 30 Tage"}>{chart}</MobileChart>,document.body)}</span>
}
function amountForCurrency(value:number,currency="USD"){return new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:2}).format(value)}

