const catalog:Record<string,string>={
  "Obst & Gemüse":"Apfel|🍎;Grüner Apfel|🍏;Birne|🍐;Orange|🍊;Zitrone|🍋;Limette|🍋;Banane|🍌;Wassermelone|🍉;Weintrauben|🍇;Erdbeeren|🍓;Heidelbeeren|🫐;Melone|🍈;Kirschen|🍒;Pfirsich|🍑;Mango|🥭;Ananas|🍍;Kokosnuss|🥥;Kiwi|🥝;Tomate|🍅;Avocado|🥑;Aubergine|🍆;Kartoffel|🥔;Karotte|🥕;Mais|🌽;Paprika|🫑;Gurke|🥒;Blattsalat|🥬;Brokkoli|🥦;Knoblauch|🧄;Zwiebel|🧅;Pilze|🍄;Erdnüsse|🥜;Kastanie|🌰;Oliven|🫒;Süßkartoffel|🍠;Ingwer|🫚;Erbsen|🫛;Kräuter|🌿",
  "Backwaren":"Brot|🍞;Baguette|🥖;Croissant|🥐;Brezel|🥨;Bagel|🥯;Pfannkuchen|🥞;Waffeln|🧇;Käsegebäck|🧀;Kuchen|🍰;Torte|🎂;Muffin|🧁;Keks|🍪;Brotstange|🥖;Toastbrot|🍞;Donut|🍩;Zimtschnecke|🥐;Cracker|🍘;Reiswaffeln|🍘;Semmel|🥯",
  "Milchprodukte":"Milch|🥛;Butter|🧈;Käse|🧀;Ei|🥚;Joghurt|🥣;Sahne|🥛;Topfen|🥣;Quark|🥣;Frischkäse|🧀;Mozzarella|🧀;Parmesan|🧀;Feta|🧀;Gouda|🧀;Pudding|🍮;Eiscreme|🍨;Softeis|🍦;Milchshake|🥤;Haferdrink|🥛;Schmand|🥣;Kefir|🥛;Skyr|🥣;Margarine|🧈;Eierkarton|🥚",
  "Fleisch & Fisch":"Huhn|🍗;Hähnchen|🍗;Steak|🥩;Fleisch|🍖;Speck|🥓;Wurst|🌭;Burger|🍔;Fisch|🐟;Lachs|🐟;Thunfisch|🐟;Garnele|🦐;Krabbe|🦀;Muscheln|🦪;Sushi|🍣;Fischstäbchen|🐟;Hackfleisch|🥩;Schinken|🥓;Pute|🍗;Tofu|🧈",
  "Nudeln & Reis":"Spaghetti|🍝;Nudeln|🍝;Pasta|🍝;Lasagne|🍝;Ravioli|🥟;Makkaroni|🍝;Reis|🍚;Reisschale|🍚;Risotto|🍚;Couscous|🍚;Quinoa|🌾;Haferflocken|🥣;Müsli|🥣;Cornflakes|🥣;Mehl|🌾;Linsen|🫘;Bohnen|🫘;Kichererbsen|🫘;Polenta|🌽;Kartoffelpüree|🥔",
  "Getränke":"Wasser|💧;Mineralwasser|💧;Kaffee|☕;Tee|🍵;Grüner Tee|🍵;Saft|🧃;Orangensaft|🍊;Apfelsaft|🍎;Limonade|🥤;Cola|🥤;Eistee|🧋;Energy-Drink|⚡;Bier|🍺;Wein|🍷;Sekt|🥂;Milchkaffee|☕;Kakao|☕;Smoothie|🥤;Kokosdrink|🥥;Sirup|🍯;Trinkflasche|🧴;Thermoskanne|☕",
  "Snacks":"Chips|🍿;Popcorn|🍿;Schokolade|🍫;Pralinen|🍬;Bonbons|🍬;Gummibärchen|🍬;Lutscher|🍭;Kaugummi|🍬;Nüsse|🥜;Salzstangen|🥨;Cracker|🍘;Tortilla-Chips|🌮;Nachos|🧀;Energieriegel|🍫;Müsliriegel|🥜;Pudding|🍮;Gelee|🍮;Marshmallows|🍡;Kekse|🍪;Studentenfutter|🥜",
  "Haushalt":"Toilettenpapier|🧻;Küchenrolle|🧻;Taschentücher|🤧;Spülmittel|🧴;Waschmittel|🧺;Weichspüler|🧴;Schwamm|🧽;Reinigungsmittel|🧹;Allzweckreiniger|🧴;Glasreiniger|🪟;Müllbeutel|🗑️;Alufolie|🧻;Backpapier|📜;Frischhaltefolie|🧻;Geschirrspültabs|🫧;Handseife|🧼;Shampoo|🧴;Duschgel|🧴;Zahnpasta|🪥;Zahnbürste|🪥;Deo|🧴;Rasierer|🪒;Batterien|🔋;Glühbirne|💡;Kerzen|🕯️;Pflaster|🩹;Staubsaugerbeutel|🧹",
  "Sonstiges":"Blumen|💐;Pflanze|🪴;Hundefutter|🐶;Katzenfutter|🐱;Tierfutter|🐾;Büromaterial|✏️;Stift|🖊️;Notizbuch|📓;Batterie|🔋;Geschenkpapier|🎁;Servietten|🧻;Grillkohle|🔥;Holz|🪵;Klebeband|📦;Paket|📦;Schuhcreme|👞;Sonnencreme|☀️;Insektenschutz|🦟;Medikamente|💊;Vitamine|💊"
};

export const productIcons=Object.entries(catalog).flatMap(([category,entries])=>entries.split(";").map(entry=>{const [name,emoji]=entry.split("|");return{name,emoji,category}}));
export const productIconCategories=["Alle",...Object.keys(catalog)];

const productAliases:Record<string,string>={"warm water":"wasser","hot water":"wasser","cold water":"wasser","boiling water":"wasser","black coffee":"kaffee","white coffee":"kaffee","instant coffee":"kaffee","coffee beans":"kaffee","spring onion":"zwiebel","green onion":"zwiebel","bell pepper":"paprika","capsicum":"paprika","aubergine":"aubergine","eggplant":"aubergine","courgette":"zucchini","zucchini":"zucchini","coriander":"kräuter","cilantro":"kräuter","chickpeas":"kichererbsen","garbanzo beans":"kichererbsen","toilet paper":"toilettenpapier","kitchen roll":"küchenrolle","dish soap":"spülmittel","washing-up liquid":"spülmittel","laundry detergent":"waschmittel","sparkling water":"mineralwasser","still water":"wasser","ground coffee":"kaffee","coffee powder":"kaffee","tomato":"tomate","tomatoes":"tomate","potatoes":"kartoffel","carrots":"karotte","cucumbers":"gurke","bananas":"banane","apples":"apfel","eggs":"ei","onions":"zwiebel","chicken breast":"huhn","chicken":"huhn","beef":"fleisch","pork":"fleisch","fish":"fisch","rice":"reis","pasta":"nudeln","noodles":"nudeln","bread":"brot","cheese":"käse","milk":"milch","butter":"butter","yogurt":"joghurt","yoghurt":"joghurt","flour":"mehl","sugar":"zucker","salt":"salz","olive oil":"öl","vegetable oil":"öl","oil":"öl","apple juice":"saft","orange juice":"saft"};
function normalizeProductSearch(value:string){return value.toLocaleLowerCase("de").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ß/g,"ss").replace(/[^a-z0-9 ]/g," ").replace(/\s+/g," ").trim()}
export function matchProductIcon(query:string){const normalized=normalizeProductSearch(query);if(!normalized)return undefined;const aliased=normalizeProductSearch(productAliases[normalized]??normalized);const exact=productIcons.find(item=>normalizeProductSearch(item.name)===aliased);if(exact)return exact;const words=aliased.split(" ").filter(word=>word.length>2);return productIcons.map(item=>{const name=normalizeProductSearch(item.name);const score=(name===aliased?100:0)+(name.length>3&&aliased.includes(name)?40:0)+(aliased.length>3&&name.includes(aliased)?30:0)+words.reduce((sum,word)=>sum+(name.split(" ").includes(word)?8:0),0);return{item,score}}).filter(result=>result.score>=8).sort((a,b)=>b.score-a.score||a.item.name.length-b.item.name.length)[0]?.item}
