"use client";

import {useRef,useState,type ChangeEvent} from "react";
import {createPortal} from "react-dom";
import {ArrowLeft,Check,FileUp,LoaderCircle,Plus,Receipt,Trash2,X} from "lucide-react";
import {parseReceiptText,type ParsedReceipt, type ReceiptLine} from "./shopping-receipt-parser";
import {parseMoneyAmount} from "@/lib/money";

type Props={buyer:string;store:string;layout:"tiles"|"list";onClose:()=>void;onSaved:()=>void};
const isoToday=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const euro=(n:number)=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(n);
const id=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;

export function ShoppingReceiptImport({buyer,store,layout,onClose,onSaved}:Props){
 const [file,setFile]=useState<File|null>(null);const [parsed,setParsed]=useState<ParsedReceipt|null>(null);const [lines,setLines]=useState<ReceiptLine[]>([]);const [receiptStore,setReceiptStore]=useState(store);const [date,setDate]=useState(isoToday());const [total,setTotal]=useState("");const [progress,setProgress]=useState(0);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [editingPrice,setEditingPrice]=useState<string|null>(null);const input=useRef<HTMLInputElement>(null);
 const sum=lines.reduce((value,line)=>value+(line.price??0),0);const shownTotal=total|| (sum?new Intl.NumberFormat("de-AT",{minimumFractionDigits:2,maximumFractionDigits:2}).format(sum):"");
 async function readFile(file:File){if(!file.type.startsWith("image/")){setError("Bitte ein Foto oder Bild vom Kassenzettel auswählen.");return}if(file.size>10*1024*1024){setError("Das Bild darf höchstens 10 MB groß sein.");return}setFile(file);setParsed(null);setLines([]);setError("");setProgress(0);setStatus("Texterkennung wird vorbereitet …");setBusy(true);let worker:Awaited<ReturnType<typeof import("tesseract.js").createWorker>>|undefined;try{const {createWorker}=await import("tesseract.js");worker=await createWorker("deu",1,{logger:message=>{if(typeof message.progress==="number")setProgress(Math.round(message.progress*100));if(message.status)setStatus(message.status)}});const result=await worker.recognize(file);const receipt=parseReceiptText(result.data.text);setParsed(receipt);setLines(receipt.lines);setReceiptStore(receipt.store==="Andere"?store:receipt.store);setDate(receipt.date||isoToday());setTotal("");if(!receipt.lines.length)setError("Der Bon wurde gelesen, aber keine Artikelzeilen erkannt. Du kannst Artikel manuell ergänzen.");setStatus("")}catch(cause){setError(cause instanceof Error?`Texterkennung fehlgeschlagen: ${cause.message}`:"Texterkennung fehlgeschlagen.");setStatus("")}finally{if(worker)await worker.terminate();setBusy(false)}}
 function updateLine(lineId:string,patch:Partial<ReceiptLine>){setLines(current=>current.map(line=>line.id===lineId?{...line,...patch}:line))}
 async function save(){const amount=total.trim()?parseMoneyAmount(total):sum;if(!Number.isFinite(amount)||amount<=0){setError("Bitte einen gültigen Gesamtbetrag eingeben.");return}if(!file){setError("Bitte zuerst den Kassenzettel fotografieren oder auswählen.");return}setBusy(true);setError("");let receiptId="";try{const form=new FormData();form.set("file",file);const upload=await fetch("/api/receipts",{method:"POST",body:form});const uploaded=await upload.json();if(!upload.ok)throw new Error(uploaded.error||"Der Beleg konnte nicht gespeichert werden.");receiptId=uploaded.receiptId;const response=await fetch("/api/bookings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"out",title:`Einkauf · ${new Intl.DateTimeFormat("de-AT").format(new Date(`${date}T12:00:00`))}`,amount,recipient:receiptStore,method:"Karte / Überweisung",date,detail:`Bezahlt von ${buyer}`,purchase:{store:receiptStore,buyer,items:lines.map(({name,qty,price,icon})=>({name:name.trim(),qty:qty.trim()||"1 Stück",price:price===null?null:Math.round(price*100)/100,icon})).filter(line=>line.name),receiptId,receiptName:file.name,receiptType:file.type}})});const saved=await response.json();if(!response.ok)throw new Error(saved.error||"Die Buchungszeile konnte nicht gespeichert werden.");onSaved()}catch(cause){if(receiptId)void fetch(`/api/receipts?id=${encodeURIComponent(receiptId)}`,{method:"DELETE"});setError(cause instanceof Error?cause.message:"Der Beleg konnte nicht gebucht werden.")}finally{setBusy(false)}}
 function addLine(){setLines(current=>[...current,{id:id(),name:"",qty:"1 Stück",price:null,icon:"🛒",confidence:"check"}])}
 return createPortal(<div className="receipt-import-scrim" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose()}}><section className={`receipt-import-dialog receipt-import-${layout}`} role="dialog" aria-modal="true" aria-labelledby="receipt-import-title"><header className="receipt-import-header"><button className="receipt-import-back" onClick={onClose} aria-label="Zurück"><ArrowLeft size={18}/></button><div><small>Haushaltskonto · {buyer} · {receiptStore}</small><h2 id="receipt-import-title">Einkauf per Bon</h2></div><button className="sheet-close" onClick={onClose} aria-label="Schließen"><X size={19}/></button></header><div className="receipt-import-body">
 {!file&&<><p>Bon abfotografieren oder Bild auswählen. Artikel, Preise und Datum werden vor dem Buchen geprüft.</p><button className="receipt-file-pick" onClick={()=>input.current?.click()}><Receipt size={24}/><b>Bon fotografieren oder hochladen</b><small>JPG, PNG oder WebP · Texterkennung läuft lokal am Gerät</small></button><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(event:ChangeEvent<HTMLInputElement>)=>{const selected=event.currentTarget.files?.[0];if(selected)void readFile(selected)}}/></>}
 {file&&<><div className="receipt-file-name"><FileUp size={16}/><span>{file.name}</span><button onClick={()=>{setFile(null);setParsed(null);setLines([]);setError("")}}>Anderes Bild</button></div>{busy&&<div className="receipt-ocr-progress"><LoaderCircle size={17} className="receipt-spinner"/><span>{status||"Bon wird gelesen …"}</span><b>{progress}%</b><div><i style={{width:`${progress}%`}}/></div></div>}{parsed&&!busy&&<><div className="receipt-fields"><label>Laden<select value={receiptStore} onChange={event=>setReceiptStore(event.target.value)}>{["Billa","Spar","Hofer","Andere"].map(value=><option key={value}>{value}</option>)}</select></label><label>Datum<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label></div><div className="receipt-review-heading"><b>{lines.length} Artikel geprüft</b><small>{parsed.confidence}% Erkennungssicherheit · Werte bitte kurz kontrollieren</small></div><div className="receipt-review-list">{lines.map(line=><article className={`receipt-review-item ${line.confidence==="check"?"needs-check":""}`} key={line.id}><span className="receipt-review-icon">{line.icon}</span><input aria-label="Artikel" value={line.name} placeholder="Artikel" onChange={event=>updateLine(line.id,{name:event.target.value})}/><input aria-label="Menge" value={line.qty} onChange={event=>updateLine(line.id,{qty:event.target.value})}/>{line.price!==null||editingPrice===line.id?<input aria-label="Preis" inputMode="decimal" value={line.price===null?"":String(line.price).replace(".",",")} onChange={event=>updateLine(line.id,{price:event.target.value.trim()?parseMoneyAmount(event.target.value):null})} placeholder="Preis"/>:<button className="receipt-add-price" onClick={()=>setEditingPrice(line.id)}>+ Preis</button>}<button className="receipt-remove-line" aria-label="Artikel entfernen" onClick={()=>setLines(current=>current.filter(item=>item.id!==line.id))}><Trash2 size={14}/></button></article>)}</div><button className="receipt-add-item" onClick={addLine}><Plus size={15}/> Artikel ergänzen</button><label className="receipt-total">Gesamtbetrag<input inputMode="decimal" value={shownTotal} onChange={event=>setTotal(event.target.value)} placeholder="0,00"/></label>{parsed.total!==null&&<small className="receipt-bon-total">Summe am Bon: {euro(parsed.total)} · Artikelsumme wird automatisch berechnet.</small>}</>}{error&&<p className="receipt-import-error" role="alert">{error}</p>}</>}
 </div>{parsed&&!busy&&<footer className="receipt-import-footer"><button className="button button-quiet" onClick={onClose} disabled={busy}>Abbrechen</button><button className="button button-primary" onClick={()=>void save()} disabled={busy||!lines.some(line=>line.name.trim())}><Check size={16}/>{busy?"Wird gebucht …":"Zeile buchen"}</button></footer>}</section></div>,document.body)
}
