"use client";

import {useEffect,useRef,useState,type ChangeEvent} from "react";
import {createPortal} from "react-dom";
import {ArrowLeft,Camera,Check,FileUp,LoaderCircle,Plus,Receipt,Trash2,X} from "lucide-react";
import {parseReceiptText,type ParsedReceipt, type ReceiptLine} from "./shopping-receipt-parser";
import {parseMoneyAmount} from "@/lib/money";

type Props={buyer:string;store:string;layout:"tiles"|"list";onClose:()=>void;onSaved:()=>void};
const isoToday=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const euro=(n:number)=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(n);
const id=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;

export function ShoppingReceiptImport({buyer,store,layout,onClose,onSaved}:Props){
 const [file,setFile]=useState<File|null>(null);const [parsed,setParsed]=useState<ParsedReceipt|null>(null);const [lines,setLines]=useState<ReceiptLine[]>([]);const [receiptStore,setReceiptStore]=useState(store);const [date,setDate]=useState(isoToday());const [total,setTotal]=useState("");const [progress,setProgress]=useState(0);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [missingPriceIds,setMissingPriceIds]=useState<string[]>([]);const [mobile,setMobile]=useState(false);const [cameraError,setCameraError]=useState("");const [cameraReady,setCameraReady]=useState(false);const input=useRef<HTMLInputElement>(null);const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);
 function stopCamera(){stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;setCameraReady(false)}
 useEffect(()=>{setMobile(window.matchMedia("(max-width: 760px)").matches)},[]);
 useEffect(()=>{if(!mobile||file)return;if(!navigator.mediaDevices?.getUserMedia){setCameraError("Kamera nicht verfügbar. Bitte unten ein Foto hochladen.");return}let cancelled=false;setCameraError("");void navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false}).then(media=>{if(cancelled){media.getTracks().forEach(track=>track.stop());return}stream.current=media;if(video.current){video.current.srcObject=media;void video.current.play().then(()=>setCameraReady(true)).catch(()=>setCameraError("Kamera konnte nicht gestartet werden."))}}).catch(()=>setCameraError("Kamerazugriff nicht verfügbar. Du kannst unten ein Foto hochladen."));return()=>{cancelled=true;stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;setCameraReady(false)}},[mobile,file]);
 const sum=lines.reduce((value,line)=>value+(line.price!==null&&line.price>0?line.price:0),0);const shownTotal=total|| (sum?new Intl.NumberFormat("de-AT",{minimumFractionDigits:2,maximumFractionDigits:2}).format(sum):"");
 async function readFile(file:File){if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setError("Bitte ein Foto als JPG, PNG oder WebP auswählen.");return}if(file.size>10*1024*1024){setError("Das Bild darf höchstens 10 MB groß sein.");return}stopCamera();setFile(file);setParsed(null);setLines([]);setError("");setProgress(0);setStatus("Texterkennung wird vorbereitet …");setBusy(true);let worker:Awaited<ReturnType<typeof import("tesseract.js").createWorker>>|undefined;try{const {createWorker}=await import("tesseract.js");worker=await createWorker("deu",1,{logger:message=>{if(typeof message.progress==="number")setProgress(Math.round(message.progress*100));if(message.status)setStatus(message.status)}});const result=await worker.recognize(file);const receipt=parseReceiptText(result.data.text);setParsed(receipt);setLines(receipt.lines);setReceiptStore(receipt.store==="Andere"?store:receipt.store);setDate(receipt.date||isoToday());setTotal("");if(!receipt.lines.length)setError("Der Bon wurde gelesen, aber keine Artikelzeilen erkannt. Du kannst Artikel manuell ergänzen.");setStatus("")}catch(cause){setError(cause instanceof Error?`Texterkennung fehlgeschlagen: ${cause.message}`:"Texterkennung fehlgeschlagen.");setStatus("")}finally{if(worker)await worker.terminate();setBusy(false)}}
 async function capturePhoto(){const element=video.current;if(!element||!element.videoWidth){setCameraError("Kamera wird noch gestartet. Bitte kurz warten.");return}const canvas=document.createElement("canvas");canvas.width=element.videoWidth;canvas.height=element.videoHeight;canvas.getContext("2d")?.drawImage(element,0,0,canvas.width,canvas.height);const photo=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.9));if(!photo){setCameraError("Das Foto konnte nicht aufgenommen werden.");return}void readFile(new File([photo],`kassenzettel-${Date.now()}.jpg`,{type:"image/jpeg"}))}
 function updateLine(lineId:string,patch:Partial<ReceiptLine>){setLines(current=>current.map(line=>line.id===lineId?{...line,...patch}:line))}
 async function save(){const priced=lines.filter(line=>line.name.trim()&&line.price!==null&&line.price>0);const missing=lines.filter(line=>line.name.trim()&&(line.price===null||line.price<=0));if(priced.length&&missing.length){setMissingPriceIds(missing.map(line=>line.id));setError("Einige Artikelpreise fehlen. Prüfe die rot markierten Felder, damit die Artikelsumme stimmt.");const first=missing[0];requestAnimationFrame(()=>document.querySelector(`[data-receipt-line-id="${first.id}"]`)?.scrollIntoView({behavior:"smooth",block:"center"}));window.setTimeout(()=>setMissingPriceIds([]),2400);return}const amount=total.trim()?parseMoneyAmount(total):sum;if(!Number.isFinite(amount)||amount<=0){setError("Bitte einen gültigen Gesamtbetrag eingeben.");return}if(!file){setError("Bitte zuerst den Kassenzettel fotografieren oder auswählen.");return}setBusy(true);setError("");let receiptId="";try{const form=new FormData();form.set("file",file);const upload=await fetch("/api/receipts",{method:"POST",body:form});const uploaded=await upload.json();if(!upload.ok)throw new Error(uploaded.error||"Der Beleg konnte nicht gespeichert werden.");receiptId=uploaded.receiptId;const response=await fetch("/api/bookings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"out",title:`Einkauf · ${new Intl.DateTimeFormat("de-AT").format(new Date(`${date}T12:00:00`))}`,amount,recipient:receiptStore,method:"Karte / Überweisung",date,detail:`Bezahlt von ${buyer}`,purchase:{store:receiptStore,buyer,items:lines.map(({name,qty,price,icon})=>({name:name.trim(),qty:qty.trim()||"1 Stück",price:price!==null&&price>0?Math.round(price*100)/100:null,icon})).filter(line=>line.name),receiptId,receiptName:file.name,receiptType:file.type}})});const saved=await response.json();if(!response.ok)throw new Error(saved.error||"Die Buchungszeile konnte nicht gespeichert werden.");onSaved()}catch(cause){if(receiptId)void fetch(`/api/receipts?id=${encodeURIComponent(receiptId)}`,{method:"DELETE"});setError(cause instanceof Error?cause.message:"Der Beleg konnte nicht gebucht werden.")}finally{setBusy(false)}}
 function addLine(){setLines(current=>[...current,{id:id(),name:"",qty:"1 Stück",price:null,icon:"🛒",confidence:"check"}])}
 return createPortal(<div className="receipt-import-scrim" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose()}}><section className={`receipt-import-dialog receipt-import-${layout}`} role="dialog" aria-modal="true" aria-labelledby="receipt-import-title"><header className="receipt-import-header"><button className="receipt-import-back" onClick={onClose} aria-label="Zurück"><ArrowLeft size={18}/></button><div><small>Haushaltskonto · {buyer} · {receiptStore}</small><h2 id="receipt-import-title">Einkauf per Bon</h2></div><button className="sheet-close" onClick={onClose} aria-label="Schließen"><X size={19}/></button></header><div className="receipt-import-body">
 {!file&&<><p className="receipt-intro">Bon fotografieren oder ein vorhandenes Foto auswählen. Artikel, Preise und Datum kannst du vor dem Buchen korrigieren.</p>{mobile?<><div className={`receipt-camera-view ${cameraReady?"is-live":""}`}><video ref={video} autoPlay playsInline muted/>{!cameraReady&&<div className="receipt-camera-placeholder"><Receipt size={30}/><b>{cameraError||"Kamera wird geöffnet …"}</b><small>Erlaube den Kamerazugriff für ein Livebild.</small></div>}<span className="receipt-camera-badge">KASSENZETTEL</span></div><button className="receipt-camera-capture" onClick={()=>void capturePhoto()} disabled={!cameraReady}><Camera size={18}/> Foto aufnehmen</button><button className="receipt-upload-button" onClick={()=>input.current?.click()}><FileUp size={16}/> Foto aus Dateien hochladen</button></>:<button className="receipt-file-pick" onClick={()=>input.current?.click()}><FileUp size={23}/><b>Datei auswählen</b><small>Explorer öffnen · JPG, PNG oder WebP</small></button>}<input ref={input} type="file" accept="image/jpeg,image/png,image/webp" onChange={(event:ChangeEvent<HTMLInputElement>)=>{const selected=event.currentTarget.files?.[0];if(selected)void readFile(selected)}}/></>}
 {file&&<><div className="receipt-file-name"><FileUp size={16}/><span>{file.name}</span><button onClick={()=>{setFile(null);setParsed(null);setLines([]);setError("");if(input.current)input.current.value=""}}>Anderes Bild</button></div>{busy&&<div className="receipt-ocr-progress"><LoaderCircle size={17} className="receipt-spinner"/><span>{status||"Bon wird gelesen …"}</span><b>{progress}%</b><div><i style={{width:`${progress}%`}}/></div></div>}{parsed&&!busy&&<><div className="receipt-fields"><label>Laden<select value={receiptStore} onChange={event=>setReceiptStore(event.target.value)}>{["Billa","Spar","Hofer","Andere"].map(value=><option key={value}>{value}</option>)}</select></label><label>Datum<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label></div><div className="receipt-review-heading"><b>{lines.length} Artikel geprüft</b><small>{parsed.confidence}% Erkennungssicherheit · Werte bitte kurz kontrollieren</small></div><div className="receipt-review-list">{lines.map(line=><article className={`receipt-review-item ${line.confidence==="check"?"needs-check":""} ${missingPriceIds.includes(line.id)?"missing-price":""}`} data-receipt-line-id={line.id} key={line.id}><span className="receipt-review-icon">{line.icon}</span><input aria-label="Artikel" value={line.name} placeholder="Artikel" onChange={event=>updateLine(line.id,{name:event.target.value})}/><input aria-label="Menge" value={line.qty} onChange={event=>updateLine(line.id,{qty:event.target.value})}/><input aria-label={`Preis für ${line.name||"Artikel"}`} inputMode="decimal" value={line.price===null?"":String(line.price).replace(".",",")} onChange={event=>updateLine(line.id,{price:event.target.value.trim()?parseMoneyAmount(event.target.value):null})} placeholder="Preis"/><button className="receipt-remove-line" aria-label="Artikel entfernen" onClick={()=>setLines(current=>current.filter(item=>item.id!==line.id))}><Trash2 size={14}/></button></article>)}</div><button className="receipt-add-item" onClick={addLine}><Plus size={15}/> Artikel ergänzen</button><label className="receipt-total">Gesamtbetrag<input inputMode="decimal" value={shownTotal} onChange={event=>setTotal(event.target.value)} placeholder="0,00"/></label>{parsed.total!==null&&<small className="receipt-bon-total">Summe am Bon: {euro(parsed.total)} · Artikelsumme wird automatisch berechnet.</small>}</>}{error&&<p className="receipt-import-error" role="alert">{error}</p>}</>}
 </div>{parsed&&!busy&&<footer className="receipt-import-footer"><button className="button button-quiet" onClick={onClose} disabled={busy}>Abbrechen</button><button className="button button-primary" onClick={()=>void save()} disabled={busy||!lines.some(line=>line.name.trim())}><Check size={16}/>{busy?"Wird gebucht …":"Zeile buchen"}</button></footer>}</section></div>,document.body)
}
