"use client";

import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";
import {ArrowLeft,Check,ChevronRight,Receipt,ShoppingCart,X} from "lucide-react";
import {useHouseholdState} from "@/lib/use-household-state";
import {triggerHaptic} from "@/lib/haptics";
import {parseMoneyAmount} from "@/lib/money";
import {ShoppingReceiptImport} from "./shopping-receipt-import";

export type ShoppingRunItem={id:string;name:string;cat:string;icon:string;qty:string;note?:string};
type Run={buyer:string;store:string;sortByAisle:boolean;trackPrices?:boolean;paymentMethod?:"Bar"|"Karte persönlich"|"Karte Wohnung";checked:string[];category:string;startedAt:string};
type PurchaseLog={store:string;buyer:string;items:{name:string;qty:string;price:number|null;icon:string}[]};
type DebtEvent={id:number;direction:"debt";from:string;to:string;amount:number;purpose:string;method:string;date:string;purchase?:PurchaseLog};
type Props={items:ShoppingRunItem[];setItems:(next:ShoppingRunItem[]|((current:ShoppingRunItem[])=>ShoppingRunItem[]))=>void;layout:"tiles"|"list"};
const stores=["Billa","Spar","Hofer"];
const initialRun:Run|null=null;
const eur=(amount:number)=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(amount);

export function ShoppingStartModule({items,setItems,layout}:Props){
 const [run,setRun,ready]=useHouseholdState<Run|null>("shoppingStartRun",initialRun);
 const [debtEvents,setDebtEvents]=useHouseholdState<DebtEvent[]>("debtEvents",[]);
 const [preferences]=useHouseholdState<{shoppingHaptics?:boolean}>("preferences",{});
 const [stage,setStage]=useState<"setup"|"shop"|"finish"|null>(null);
 const [buyer,setBuyer]=useState("Marcel");const [store,setStore]=useState("Billa");const [otherStore,setOtherStore]=useState("");const [sortByAisle,setSortByAisle]=useState(true);
 const [outcomeItem,setOutcomeItem]=useState<ShoppingRunItem|null>(null);const [quantityItem,setQuantityItem]=useState<ShoppingRunItem|null>(null);const [quantityDraft,setQuantityDraft]=useState("");const [prices,setPrices]=useState<Record<string,string>>({});const [missingPriceId,setMissingPriceId]=useState<string|null>(null);const [total,setTotal]=useState("");const [receiptOpen,setReceiptOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 const categories=useMemo(()=>{const source=items.filter(item=>!run?.checked.includes(item.id));return run&&!run.sortByAisle&&source.length?["Alle Artikel"]:[...new Set(source.map(item=>item.cat))]},[items,run]);
 function haptic(){triggerHaptic(preferences.shoppingHaptics!==false)}
 const grouped=useMemo(()=>{const map=new Map<string,ShoppingRunItem[]>();for(const item of items){if(run?.checked.includes(item.id))continue;const key=run&&!run.sortByAisle?"Alle Artikel":item.cat;map.set(key,[...(map.get(key)||[]),item])}return [...map.entries()]},[items,run]);
 const category=run?.category||categories[0]||"";const inCategory=items.filter(item=>(run&&!run.sortByAisle||item.cat===category)&&!run?.checked.includes(item.id));const completed=run?.checked.length||0;const trackedPriceTotal=run?.checked.reduce((sum,id)=>{const price=parseMoneyAmount(prices[id]||"");return sum+(Number.isFinite(price)&&price>0?price:0)},0)||0;const checkedItems=items.filter(item=>run?.checked.includes(item.id));const hasSomePrices=checkedItems.some(item=>{const value=parseMoneyAmount(prices[item.id]||"");return Number.isFinite(value)&&value>0});const hasMissingPrices=hasSomePrices&&checkedItems.some(item=>{const value=parseMoneyAmount(prices[item.id]||"");return !Number.isFinite(value)||value<=0});const finalAmount=total.trim()?parseMoneyAmount(total):trackedPriceTotal;const finishDisabled=busy||hasMissingPrices||!Number.isFinite(finalAmount)||finalAmount<=0;
 useEffect(()=>{if(!ready)return;if(!run){if(stage==="shop"||stage==="finish"){setStage(null);setPrices({});setTotal("");setError("")}return}if(!items.length){setRun(null);setStage(null);setPrices({});setTotal("");setError("");setMissingPriceId(null);return}const activeIds=new Set(items.map(item=>item.id));const checked=run.checked.filter(id=>activeIds.has(id));const remainingCategories=[...new Set(items.filter(item=>!checked.includes(item.id)).map(item=>run.sortByAisle?item.cat:"Alle Artikel"))];const nextCategory=remainingCategories.includes(run.category)?run.category:remainingCategories[0]||run.category;if(checked.length!==run.checked.length||nextCategory!==run.category)setRun(current=>current?{...current,checked,category:nextCategory}:current)},[items,ready,run,setRun,stage]);
 function abortPurchase(){setRun(null);setStage(null);setPrices({});setTotal("");setError("");setMissingPriceId(null)}
 function start(){if(!items.length){setError("Die Einkaufsliste ist noch leer.");return}const next:Run={buyer,store:store==="Andere"?(otherStore.trim()||"Anderer Laden"):store,sortByAisle,paymentMethod:"Karte Wohnung",checked:[],category:sortByAisle?items[0].cat:"Alle Artikel",startedAt:new Date().toISOString()};setRun(next);setError("");setStage("shop")}
 function mark(item:ShoppingRunItem){if(!run)return;haptic();setRun({...run,checked:[...run.checked,item.id]});setPrices(current=>({...current,[item.id]:current[item.id]||""}))}
 function finishCategory(){if(!run)return;haptic();const next=categories.find(value=>value!==category);const completedIds=inCategory.map(item=>item.id);setRun({...run,checked:[...new Set([...run.checked,...completedIds])],...(next?{category:next}:{})});if(!next)setStage("finish")}
 function resolveItem(action:"later"|"expensive"|"remove"){if(!outcomeItem)return;if(action==="remove"){haptic();setItems(current=>current.filter(item=>item.id!==outcomeItem.id))}setOutcomeItem(null)}
 async function finishPurchase(){if(!run)return;const checked=items.filter(item=>run.checked.includes(item.id));const entered=checked.filter(item=>{const price=parseMoneyAmount(prices[item.id]||"");return Number.isFinite(price)&&price>0});const missing=checked.find(item=>{const price=parseMoneyAmount(prices[item.id]||"");return !Number.isFinite(price)||price<=0});if(entered.length&&missing){setMissingPriceId(missing.id);setError("Einige Artikelpreise fehlen. Bitte die rot markierte Zeile ergänzen.");window.setTimeout(()=>setMissingPriceId(null),2200);requestAnimationFrame(()=>document.getElementById(`shopping-price-${missing.id}`)?.scrollIntoView({behavior:"smooth",block:"center"}));return}setBusy(true);setError("");try{const priceSum=run.checked.reduce((sum,id)=>{const price=parseMoneyAmount(prices[id]||"");return sum+(Number.isFinite(price)&&price>0?price:0)},0);const amount=total.trim()?parseMoneyAmount(total):priceSum;if(!Number.isFinite(amount)||amount<=0)throw new Error("Bitte den Gesamtbetrag oder Artikelpreise eingeben.");const date=new Intl.DateTimeFormat("de-AT",{timeZone:"Europe/Vienna"}).format(new Date());const purchase:PurchaseLog={store:run.store,buyer:run.buyer,items:checked.map(item=>{const value=parseMoneyAmount(prices[item.id]||"");return{name:item.name,qty:item.qty,price:Number.isFinite(value)&&value>0?Math.round(value*100)/100:null,icon:item.icon}})};const paymentMethod=run.paymentMethod||"Karte Wohnung";if(paymentMethod!=="Karte Wohnung"){const owes=run.buyer==="Marcel"?"Philip":"Marcel";const debt:DebtEvent={id:Date.now(),direction:"debt",from:owes,to:run.buyer,amount:Math.round(amount*100)/100,purpose:`Einkauf übernommen · ${run.store}`,method:paymentMethod==="Bar"?"Bar":"Karte persönlich",date,purchase};setDebtEvents(current=>[debt,...current])}else{const response=await fetch("/api/bookings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"out",title:`Einkauf · ${date}`,amount,recipient:run.store,method:"Karte Wohnung",date,detail:`Bezahlt von ${run.buyer}`,purchase})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Buchung fehlgeschlagen.")}
   setItems(current=>current.filter(item=>!run.checked.includes(item.id)));setRun(null);setStage(null);setOutcomeItem(null);setTotal("");
  }catch(cause){setError(cause instanceof Error?cause.message:"Der Einkauf konnte nicht abgeschlossen werden.")}finally{setBusy(false)}}
 if(!ready)return null;
 return <>
  <button className={`shopping-start-launch ${run?"has-active-run":""}`} onClick={()=>{setError("");setStage(run?"shop":"setup")}}><ShoppingCart size={19}/><span>{run?"Einkauf fortsetzen":"Einkauf buchen"}</span>{run&&<small>{completed} erledigt</small>}</button>
  {stage&&createPortal(<div className="shopping-start-scrim" onMouseDown={event=>{if(event.target===event.currentTarget&&stage==="setup")setStage(null)}}><section className={`shopping-start-dialog shopping-start-${stage} ${layout==="list"?"shopping-start-list-layout":"shopping-start-tile-layout"}`} role="dialog" aria-modal="true" aria-label="Einkauf starten" onMouseDown={event=>event.stopPropagation()}>
   <header className="shopping-start-header">{stage!=="setup"&&<button className="shopping-start-back" onClick={()=>setStage(stage==="finish"?"shop":"setup")} aria-label="Zurück"><ArrowLeft size={18}/></button>}<div><small>{stage==="setup"?"Gemeinsam einkaufen":stage==="shop"?`${run?.store||"Einkauf"} · ${run?.buyer||""}`:"Einkauf abschließen"}</small><h2>{stage==="setup"?"Einkauf starten":stage==="shop"?"Einkauf":"Einkauf fertig"}</h2></div><button className="sheet-close" onClick={()=>setStage(null)} aria-label="Schließen"><X size={19}/></button></header>
   {stage==="setup"&&<div className="shopping-start-body"><div className="shopping-start-field"><b>Wer kauft ein?</b><div className="shopping-start-options">{["Marcel","Philip"].map(value=><button className={buyer===value?"selected":""} onClick={()=>setBuyer(value)} key={value}>{value}</button>)}</div></div><div className="shopping-start-field"><b>Welcher Laden?</b><div className="shopping-start-options">{[...stores,"Andere"].map(value=><button className={store===value?"selected":""} onClick={()=>setStore(value)} key={value}>{value}</button>)}</div>{store==="Andere"&&<input value={otherStore} onChange={event=>setOtherStore(event.target.value)} placeholder="Name des Geschäfts"/>}</div><label className="shopping-start-switch"><span><b>Nach Ladenlayout sortieren</b><small>Artikel nach Kategorien gruppieren</small></span><input type="checkbox" checked={sortByAisle} onChange={event=>setSortByAisle(event.target.checked)}/></label><button className="button button-primary shopping-start-primary" disabled={!items.length} onClick={start}><ShoppingCart size={17}/> Einkauf starten</button>{!items.length&&<small className="shopping-start-empty-hint">Füge zuerst Artikel zur Einkaufsliste hinzu oder erfasse den Einkauf per Bon.</small>}<button className="shopping-start-receipt-entry" onClick={()=>setReceiptOpen(true)}><Receipt size={16}/> Per Bon eingeben</button>{error&&<p className="shopping-start-error">{error}</p>}</div>}
   {stage==="shop"&&<div className="shopping-start-body"><div className="shopping-start-progress"><span style={{width:`${items.length?Math.min(100,completed/items.length*100):0}%`}}/></div><div className="shopping-start-progress-label">{completed} von {items.length} erledigt</div>{run?.sortByAisle&&<div className="shopping-start-category-list">{grouped.map(([name,rows])=><button className={`shopping-start-category ${category===name?"active":""}`} onClick={()=>setRun(run?{...run,category:name}:run)} key={name}><span>{rows[0]?.icon}</span><b>{name}</b><small>{rows.length} Artikel</small><ChevronRight size={16}/></button>)}</div>}{category&&grouped.length>0&&<section className="shopping-start-current">{run?.sortByAisle&&<div className="shopping-start-subhead"><b>{category}</b><small>{inCategory.length} übrig</small></div>}<div className={`shopping-start-items ${!run?.sortByAisle&&layout==="tiles"?"shopping-start-items-tiles":""}`}>{inCategory.map(item=><article className={`shopping-start-item ${missingPriceId===item.id?"missing-price": ""}`} key={item.id}><button className="shopping-start-item-main" onClick={()=>mark(item)}><span className="shopping-start-item-icon">{item.icon}</span><span><b>{item.name}</b><small>{item.qty}</small></span><Check size={18}/></button><button className="shopping-start-item-more" onClick={()=>setOutcomeItem(item)}>Nicht bekommen?</button><label className={`shopping-start-price ${missingPriceId===item.id?"missing-price-field":""}`}>Preis €<input id={`shopping-price-${item.id}`} inputMode="decimal" value={prices[item.id]||""} onChange={event=>setPrices(current=>({...current,[item.id]:event.target.value}))} placeholder="0,00"/></label></article>)}</div><button className="button button-primary shopping-start-primary" onClick={finishCategory}><Check size={16}/>{run?.sortByAisle?"Kategorie erledigt":"Ganze Liste erledigt"}</button></section>}{!grouped.length&&<button className="button button-primary shopping-start-primary" onClick={()=>setStage("finish")}>Einkauf abschließen</button>}{error&&<p className="shopping-start-error">{error}</p>}<button className="shopping-start-abort" onClick={abortPurchase}>Einkauf abbrechen</button></div>}
    {stage==="finish"&&<div className="shopping-start-body"><div className="shopping-start-complete"><span><Check size={24}/></span><b>Einkauf abschließen</b><small>{completed} Artikel ausgewählt · {run?.store}</small></div><label className="shopping-start-field"><b>Gesamtbetrag</b><input inputMode="decimal" value={total||((trackedPriceTotal)?new Intl.NumberFormat("de-AT",{minimumFractionDigits:2,maximumFractionDigits:2}).format(trackedPriceTotal):"")} onChange={event=>setTotal(event.target.value)} placeholder={trackedPriceTotal?"Summe der Artikelpreise":"0,00 €"}/></label>{checkedItems.length>0&&<div className="shopping-start-price-lines">{checkedItems.map(item=>{const empty=!(Number.isFinite(parseMoneyAmount(prices[item.id]||""))&&parseMoneyAmount(prices[item.id]||"")>0);return <label className={missingPriceId===item.id||hasMissingPrices&&empty?"missing-price-field":""} key={item.id}>{item.icon} {item.name}<input id={`shopping-price-${item.id}`} inputMode="decimal" aria-label={`Preis für ${item.name}`} value={prices[item.id]||""} onChange={event=>setPrices(current=>({...current,[item.id]:event.target.value}))} placeholder="0,00"/></label>})}</div>}{hasMissingPrices&&<p className="shopping-start-error" role="alert">Es fehlen noch Artikelpreise. Bitte die rot markierten Felder ergänzen.</p>}<div className="shopping-start-payment"><b>Bezahlt mit</b><div><button className={run?.paymentMethod==="Bar"?"selected":""} onClick={()=>{if(run)setRun({...run,paymentMethod:"Bar"})}}>Bar</button><button className={run?.paymentMethod==="Karte Wohnung"||!run?.paymentMethod?"selected":""} onClick={()=>{if(run)setRun({...run,paymentMethod:"Karte Wohnung"})}}>Karte Wohnung</button><button className={run?.paymentMethod==="Karte persönlich"?"selected":""} onClick={()=>{if(run)setRun({...run,paymentMethod:"Karte persönlich"})}}>Karte persönlich</button></div></div><button className="button button-primary shopping-start-primary" disabled={finishDisabled} onClick={()=>void finishPurchase()}><Check size={16}/>{busy?"Wird gespeichert…":"Einkauf abschließen"}</button>{error&&<p className="shopping-start-error">{error}</p>}<button className="shopping-start-abort" onClick={abortPurchase}>Einkauf abbrechen</button></div>}
  </section></div>,document.body)}
  {receiptOpen&&<ShoppingReceiptImport buyer={buyer} store={store==="Andere"?(otherStore.trim()||"Andere"):store} layout={layout} onClose={()=>setReceiptOpen(false)} onSaved={()=>{setReceiptOpen(false);setStage(null);setError("")}}/>}
  {outcomeItem&&createPortal(<div className="shopping-start-scrim"><section className="shopping-start-dialog shopping-start-outcome" role="dialog" aria-modal="true" aria-label="Artikel nicht bekommen"><header className="shopping-start-header"><div><small>{outcomeItem.qty}</small><h2>{outcomeItem.name}</h2></div><button className="sheet-close" onClick={()=>setOutcomeItem(null)} aria-label="Schließen"><X size={19}/></button></header><div className="shopping-start-body"><button className="shopping-outcome-option" onClick={()=>resolveItem("later")}><b>Nicht gefunden</b><small>Bleibt für den nächsten Einkauf</small></button><button className="shopping-outcome-option" onClick={()=>resolveItem("expensive")}><b>Zu teuer</b><small>Bleibt auf der Liste</small></button><button className="shopping-outcome-option" onClick={()=>resolveItem("remove")}><b>Heute nicht nötig</b><small>Wird jetzt entfernt</small></button><button className="shopping-outcome-option" onClick={()=>{setQuantityItem(outcomeItem);setQuantityDraft(outcomeItem.qty);setOutcomeItem(null)}}><b>Menge anpassen</b><small>Menge für diesen Einkauf ändern</small></button></div></section></div>,document.body)}
  {quantityItem&&createPortal(<div className="shopping-start-scrim"><section className="shopping-start-dialog shopping-start-outcome" role="dialog" aria-modal="true" aria-label="Menge anpassen"><header className="shopping-start-header"><div><small>Artikelmenge</small><h2>{quantityItem.name}</h2></div><button className="sheet-close" onClick={()=>setQuantityItem(null)} aria-label="Schließen"><X size={19}/></button></header><div className="shopping-start-body"><label className="shopping-start-field"><b>Menge</b><input value={quantityDraft} onChange={event=>setQuantityDraft(event.target.value)} autoComplete="off"/></label><button className="button button-primary shopping-start-primary" onClick={()=>{const item=quantityItem;const qty=quantityDraft.trim();const match=qty.match(/^\s*(\d+(?:[.,]\d+)?)/);const amount=match?Number(match[1].replace(",",".")):NaN;if(!Number.isFinite(amount)||amount<=0){setError("Die Menge muss größer als 0 sein.");return}setItems(current=>current.map(value=>value.id===item.id?{...value,qty}:value));setError("");setQuantityItem(null)}}><Check size={16}/> Menge speichern</button>{error&&<p className="shopping-start-error" role="alert">{error}</p>}</div></section></div>,document.body)}
 </>;
}
