"use client";
import {useEffect,useState} from "react";
import {Bell, Gauge, Wallet} from "lucide-react";
import {PageHeading,Panel,SectionTitle} from "@/components/ui";
import {useHouseholdState} from "@/lib/use-household-state";
import {DataBackup} from "@/components/data-backup";
import {formatMoneyInput,moneyInputProps,parseMoneyAmount} from "@/lib/money";
import {APP_VERSION} from "@/lib/app-version";

export type HouseholdPreferences={shoppingNotifications:boolean;fixedCostNotifications?:boolean;lowBalanceNotifications:boolean;marketCriticalNotifications:boolean;lowBalanceLimit:number;compactMode:boolean;reducedMotion:boolean;disableShoppingEditing:boolean;shoppingStartEnabled?:boolean;shoppingLayout?:"tiles"|"list";defaultPaymentMethod:string};
const defaults:HouseholdPreferences={shoppingNotifications:true,fixedCostNotifications:true,lowBalanceNotifications:true,marketCriticalNotifications:true,lowBalanceLimit:100,compactMode:true,reducedMotion:false,disableShoppingEditing:false,shoppingStartEnabled:false,shoppingLayout:"tiles",defaultPaymentMethod:"Überweisung"};
export default function Einstellungen(){
 const [preferences,setPreferences,ready]=useHouseholdState<HouseholdPreferences>("preferences",defaults);
 const [limitDraft,setLimitDraft]=useState("");
 useEffect(()=>{if(ready)setLimitDraft(formatMoneyInput(String(preferences.lowBalanceLimit??100)))},[ready,preferences.lowBalanceLimit]);
 const toggle=(key:"shoppingNotifications"|"lowBalanceNotifications"|"marketCriticalNotifications"|"compactMode"|"reducedMotion"|"disableShoppingEditing")=>setPreferences({...preferences,[key]:!preferences[key]});
 if(!ready)return <div className="page-stack"><PageHeading title="Einstellungen" subtitle="Gemeinsame Einstellungen werden geladen …"/><Panel><span className="loading-state">Einstellungen werden synchronisiert …</span></Panel></div>;
 return <div className="page-stack settings-page"><PageHeading eyebrow="Für eure WG" title="Einstellungen" subtitle="Schaltet nur ein, was euch im Alltag wirklich hilft. Änderungen gelten auf beiden Geräten."/><div className="content-grid two-col">
  <Panel><div className="panel-heading"><SectionTitle title="Benachrichtigungen" description="Steuern, was die Glocke oben anzeigt."/><Bell size={18}/></div><SettingRow title="Offene Einkäufe" detail="Hinweis, wenn Artikel auf der Einkaufsliste offen sind." value={preferences.shoppingNotifications} onClick={()=>toggle("shoppingNotifications")}/><SettingRow title="Niedriger Kontostand" detail="Hinweis, wenn das Wohnungskonto unter den Grenzwert fällt." value={preferences.lowBalanceNotifications} onClick={()=>toggle("lowBalanceNotifications")}/><SettingRow title="Kritische Marktmeldungen" detail="Zeigt kritische KI-, Quantum- und Kryptomeldungen in der Glocke." value={preferences.marketCriticalNotifications} onClick={()=>toggle("marketCriticalNotifications")}/><label className="setting-input"><span>Grenzwert Wohnungskonto</span><div><input {...moneyInputProps(limitDraft,setLimitDraft)} onBlur={event=>{const formatted=formatMoneyInput(event.currentTarget.value);setLimitDraft(formatted);setPreferences({...preferences,lowBalanceLimit:Math.max(0,parseMoneyAmount(formatted))})}}/><b>€</b></div></label></Panel>
  <Panel><div className="panel-heading"><SectionTitle title="Schnellbuchung" description="Vorgabe für neue Finanzbuchungen."/><Wallet size={18}/></div><label className="field-label">Zahlungsart<select value={preferences.defaultPaymentMethod} onChange={e=>setPreferences({...preferences,defaultPaymentMethod:e.target.value})}>{["Überweisung","Bar","Lastschrift","Sonstiges"].map(x=><option key={x}>{x}</option>)}</select></label><p className="setting-hint">Die Zahlungsart lässt sich bei jeder Buchung weiterhin ändern.</p></Panel>
  <Panel><div className="panel-heading"><SectionTitle title="Darstellung" description="Für schnelles Bedienen am Handy."/><Gauge size={18}/></div><SettingRow title="Kompakte Ansicht" detail="Weniger Abstand, mehr Inhalt pro Bildschirm." value={preferences.compactMode} onClick={()=>toggle("compactMode")}/><SettingRow title="Animationen überspringen" detail="Schaltet Zähler, Betragsflug und Übergänge ab." value={preferences.reducedMotion} onClick={()=>toggle("reducedMotion")}/><SettingRow title="Bearbeitung in der Einkaufsliste deaktivieren" detail="Blendet Stift und Löschen auf den Kacheln aus. Artikel verwalten bleibt als separater Bereich verfügbar." value={preferences.disableShoppingEditing} onClick={()=>toggle("disableShoppingEditing")}/><div className="setting-row shopping-layout-setting"><div><b>Einkaufsansicht</b><small>Gilt für Favoriten, alle Artikel und das Einkaufsstart-Modul.</small></div><div className="setting-choice"><button className={(preferences.shoppingLayout??"tiles")==="tiles"?"selected":""} onClick={()=>setPreferences({...preferences,shoppingLayout:"tiles"})}>Kacheln</button><button className={(preferences.shoppingLayout??"tiles")==="list"?"selected":""} onClick={()=>setPreferences({...preferences,shoppingLayout:"list"})}>Liste</button></div></div><SettingRow title="Einkauf starten" detail="Aktiviert den optionalen Einkaufsablauf mit Kategorien und Einkaufsfortschritt. Standardmäßig ausgeschaltet." value={Boolean(preferences.shoppingStartEnabled)} onClick={()=>setPreferences({...preferences,shoppingStartEnabled:!preferences.shoppingStartEnabled})}/></Panel>
  <Panel><SectionTitle title="WG-Mitglieder" description="Konten im Haushaltsbereich"/><div className="member-row"><span className="avatar">M</span><div><b>Marcel</b><small>WG-Mitglied</small></div></div><div className="member-row"><span className="avatar philip">P</span><div><b>Philip</b><small>WG-Mitglied</small></div></div><p className="setting-hint">Eure persönlichen Kontodaten werden nicht benötigt. Gemeinsame Daten bleiben auf dem WG Cockpit Server.</p></Panel>
  <DataBackup/><div className="settings-version" aria-label={`WG Cockpit Version ${APP_VERSION}`}><span>WG Cockpit</span><b>v{APP_VERSION}</b></div>
 </div></div>
}
function SettingRow({title,detail,value,onClick}:{title:string;detail:string;value:boolean;onClick:()=>void}){return <div className="setting-row"><div><b>{title}</b><small>{detail}</small></div><button className={`setting-switch ${value?"on":""}`} role="switch" aria-checked={value} aria-label={title} onClick={onClick}><i/></button></div>}
