"use client";
import { useMemo } from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import { ArrowDownLeft, ArrowUpRight, ChevronRight, Clock3, Plus, ShoppingBasket, Sparkles, Wallet } from "lucide-react";
import { PageHeading, Panel, Pill, SectionTitle } from "@/components/ui";
import { useHouseholdState } from "@/lib/use-household-state";

type Entry={id:number;kind:"in"|"out";title:string;amount:number;recipient:string;method:string;date:string};
type Debt={id:number;direction:"debt"|"repayment";from:string;to:string;amount:number;purpose:string;method:string;date:string};
type Shopping={id:string;name:string;cat:string;icon:string;qty:string};
const starter:Entry[]=[{id:1,kind:"out",title:"Miete Oktober",amount:980,recipient:"Vermieter",method:"Überweisung",date:"03.10.2026"},{id:2,kind:"in",title:"Einzahlung Marcel",amount:500,recipient:"Wohnungskonto",method:"Überweisung",date:"01.10.2026"},{id:3,kind:"out",title:"Internet",amount:49.9,recipient:"Anbieter",method:"Lastschrift",date:"01.10.2026"}];
const debtStarter:Debt[]=[{id:1,direction:"debt",from:"Philip",to:"Marcel",amount:50,purpose:"Gemeinsame Ausgaben",method:"Ausgangssaldo",date:"30.09.2026"}];
const shoppingStarter:Shopping[]=[{id:"milk",name:"Milch",cat:"Milchprodukte",icon:"🥛",qty:"2x"},{id:"eggs",name:"Eier",cat:"Milchprodukte",icon:"🥚",qty:"10 Stück"},{id:"bread",name:"Brot",cat:"Backwaren",icon:"🍞",qty:"1x"},{id:"pasta",name:"Nudeln",cat:"Nudeln & Reis",icon:"🍝",qty:"1 Packung"},{id:"cheese",name:"Käse",cat:"Milchprodukte",icon:"🧀",qty:"1x"},{id:"paper",name:"WC Papier",cat:"Haushalt",icon:"🧻",qty:"1 Packung"}];
const eur=(n:number)=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(n);
const quick=[{icon:"−",label:"Geld raus",tone:"mint"},{icon:"+",label:"Geld rein",tone:"blue"},{icon:"€",label:"Schuld begleichen",tone:"amber"},{icon:"▣",label:"Einkauf",tone:"lavender"}];
export default function Dashboard(){
 const router=useRouter();
 const [entries,,entriesReady]=useHouseholdState<Entry[]>("bookings",starter);const [balance]=useHouseholdState<number>("accountBalance",1842.54);const [debts]=useHouseholdState<Debt[]>("debtEvents",debtStarter);const [items]=useHouseholdState<Shopping[]>("shoppingItems",shoppingStarter);const [done]=useHouseholdState<string[]>("shoppingDone",[]);
 const net=useMemo(()=>debts.reduce((n,d)=>n+(d.from==="Philip"&&d.to==="Marcel"?1:-1)*(d.direction==="debt"?1:-1)*d.amount,0),[debts]);const openItems=items.filter(i=>!done.includes(i.id)).length;const monthEntries=entries.filter(e=>e.date.endsWith("10.2026"));const outgoing=monthEntries.filter(e=>e.kind==="out").reduce((n,e)=>n+e.amount,0);const incoming=monthEntries.filter(e=>e.kind==="in").reduce((n,e)=>n+e.amount,0);
 return <div className="page-stack"><PageHeading eyebrow="Euer WG-Alltag" title="Guten Tag, Marcel 👋" subtitle="Die wichtigsten Dinge für zuhause. Schnell eintragen, weitergehen." action={<span className="live-pill"><i/>Gemeinsam synchronisiert</span>}/>
  <div className="stats-grid four"><Stat icon={<Wallet size={17}/>} label="Wohnungskonto" value={entriesReady?eur(balance):"…"} sub="Gemeinsamer Kontostand"/><Stat icon={<ArrowUpRight size={17}/>} label="Philip → Marcel" value={eur(Math.max(0,net))} sub={net>0?"Offene Schuld":"Ausgeglichen"} positive={net>0}/><Stat icon={<Clock3 size={17}/>} label="Ausgaben diesen Monat" value={entriesReady?eur(outgoing):"…"} sub={`${eur(incoming)} Geld rein`}/><Stat icon={<ShoppingBasket size={17}/>} label="Einkaufsliste" value={`${openItems} offen`} sub={`${items.length} Artikel gesamt`} link="/einkauf"/></div>
  <Panel className="shortcut-panel"><div className="panel-heading"><SectionTitle title="Schnellaktionen" description="Ein Tipp öffnet die passende Eingabe"/></div><div className="shortcut-row">{quick.map(s=><button className="shortcut" key={s.label} onClick={()=>router.push(s.label==="Einkauf"?"/einkauf":"/finanzen?aktion="+encodeURIComponent(s.label))}><span className={`shortcut-icon ${s.tone}`}>{s.icon}</span><span>{s.label}</span><ChevronRight size={14}/></button>)}</div></Panel>
  <div className="content-grid dashboard-grid"><div className="main-column"><Panel><div className="panel-heading"><SectionTitle title="Letzte Bewegungen" description="Haushaltskonto · Ausgänge gehen immer vom Wohnungskonto"/><Link className="text-button" href="/finanzen">Alle Buchungen <ChevronRight size={14}/></Link></div><div className="transaction-list">{entries.slice(0,5).map(e=><div className="transaction" key={e.id}><span className={`transaction-icon ${e.kind==="in"?"green":"orange"}`}>{e.kind==="in"?<ArrowDownLeft size={17}/>:<ArrowUpRight size={17}/>}</span><div className="transaction-main"><b>{e.title}</b><small>{e.kind==="in"?`Von ${e.recipient}`:`An ${e.recipient}`} · {e.date}</small></div><strong className={`amount ${e.kind==="in"?"in-amount":"out-amount"}`}>{e.kind==="in"?"+":"−"}{eur(e.amount)}</strong></div>)}</div>{entries.length===0&&<p className="quiet-note">Noch keine Buchungen. Über „Geld raus“ oder „Geld rein“ starten.</p>}</Panel><Panel className="note-banner"><span className="banner-icon"><Sparkles size={18}/></span><div><b>Fixkosten flexibel halten</b><small>Fälligkeiten und Beträge jederzeit unter Haushaltskonto bearbeiten.</small></div><Link href="/finanzen?tab=Fixkosten" className="button button-secondary">Fixkosten öffnen</Link></Panel></div><div className="side-column"><Panel><div className="panel-heading"><SectionTitle title="Schulden & Ausgleich" description="Der aktuelle offene Betrag"/><span className="balance-avatar">€</span></div><div className="settlement"><div><small>{net>0?"Philip schuldet Marcel":net<0?"Marcel schuldet Philip":"Alles ausgeglichen"}</small><strong>{eur(Math.abs(net))}</strong></div><Link href="/finanzen?tab=ausgleich" className="button button-primary">Öffnen <ChevronRight size={14}/></Link></div><div className="settlement-foot"><span>Teilzahlungen und Tanken/Essen eintragen</span><b>{net===0?"✓":""}</b></div></Panel><Panel><div className="panel-heading"><SectionTitle title="Einkauf" description={`${openItems} Artikel noch offen`}/><ShoppingBasket size={18}/></div><div className="shopping-preview">{items.filter(i=>!done.includes(i.id)).slice(0,4).map(i=><div key={i.id}><span>{i.icon}</span><b>{i.name}</b><small>{i.qty}</small></div>)}</div><Link href="/einkauf" className="button button-secondary full-width">Einkaufsliste öffnen</Link></Panel></div></div>
 </div>
}
function Stat({icon,label,value,sub,positive,link}:{icon:React.ReactNode;label:string;value:string;sub:string;positive?:boolean;link?:string}){return <Panel className="stat-card"><div className="stat-top"><span className="stat-icon">{icon}</span><span>{label}</span></div><strong>{value}</strong><small className={positive?"positive":""}>{sub}</small>{link&&<Link aria-label="Einkauf öffnen" href={link} className="stat-link"><ChevronRight size={14}/></Link>}</Panel>}
