"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import { ArrowDownLeft, ArrowUpRight, ChevronRight, Clock3, ShoppingBasket, Wallet } from "lucide-react";
import { PageHeading, Panel, Pill, SectionTitle } from "@/components/ui";
import { useHouseholdState } from "@/lib/use-household-state";
import {parseMoneyAmount} from "@/lib/money";
import {PurchaseLogDialog,type PurchaseLogRecord} from "@/components/purchase-log-dialog";

type PurchaseLog={store:string;buyer:string;items:{name:string;qty:string;price:number|null;icon:string}[];receiptId?:string;receiptName?:string;receiptType?:string};
type Entry={id:number;kind:"in"|"out";title:string;amount:number;recipient:string;method:string;date:string;purchase?:PurchaseLog};
type Debt={id:number;direction:"debt"|"repayment";from:string;to:string;amount:number;purpose:string;method:string;date:string;purchase?:PurchaseLog};
type Shopping={id:string;name:string;cat:string;icon:string;qty:string};
const starter:Entry[]=[];
const debtStarter:Debt[]=[];
const shoppingStarter:Shopping[]=[];
type FixedRow={id:number;name:string;amount:string;active:boolean;versions?:{fromMonth:string;name:string;amount:string;active:boolean}[]};
const eur=(n:number)=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(n);
const quick=[{icon:"−",label:"Geld raus",tone:"mint"},{icon:"+",label:"Geld rein",tone:"blue"},{icon:"€",label:"Schuld begleichen",tone:"amber"},{icon:"▣",label:"Einkauf",tone:"lavender"}];
export default function Dashboard(){
 const router=useRouter();
 const [purchaseLog,setPurchaseLog]=useState<PurchaseLogRecord|null>(null);
 const [preferences]=useHouseholdState<{shoppingLayout?:"tiles"|"list"}>("preferences",{});
 const [entries,,entriesReady]=useHouseholdState<Entry[]>("bookings",starter);const [debts,,debtsReady]=useHouseholdState<Debt[]>("debtEvents",debtStarter);const [items]=useHouseholdState<Shopping[]>("shoppingItems",shoppingStarter);const [done]=useHouseholdState<string[]>("shoppingDone",[]);const [fixed]=useHouseholdState<FixedRow[]>("fixedCosts",[]);const [fixedIncomes]=useHouseholdState<FixedRow[]>("fixedIncomes",[]);
 const net=useMemo(()=>debts.reduce((n,d)=>n+(d.from==="Philip"&&d.to==="Marcel"?1:-1)*(d.direction==="debt"?1:-1)*d.amount,0),[debts]);const openItems=items.filter(i=>!done.includes(i.id)).length;const now=new Date();const month=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;const versionAt=(item:FixedRow)=>{const versions=item.versions?.length?item.versions:[{fromMonth:month,name:item.name,amount:item.amount,active:item.active}];const effective=versions.filter(version=>version.fromMonth<=month);return effective[effective.length-1]};const fixedExpenses=fixed.reduce((sum,item)=>{const version=versionAt(item);const amount=parseMoneyAmount(version?.amount||"");return sum+(version?.active?amount:0)},0);const fixedEarnings=fixedIncomes.reduce((sum,item)=>{const version=versionAt(item);const amount=parseMoneyAmount(version?.amount||"");return sum+(version?.active?amount:0)},0);const isCurrentMonth=(value:string)=>{const match=value.match(/^(\d{1,2})\.(\d{1,2})\.(\d{4})$/);if(match)return `${match[3]}-${match[2].padStart(2,"0")}`===month;const date=new Date(value);return !Number.isNaN(date.getTime())&&`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`===month};const currentEntries=entries.filter(entry=>isCurrentMonth(entry.date));const currentFixedNames=[...fixed,...fixedIncomes].map(item=>versionAt(item)?.name.toLocaleLowerCase("de")).filter((name):name is string=>Boolean(name));const actualEntries=currentEntries.filter(entry=>!currentFixedNames.some(name=>entry.title.trim().toLocaleLowerCase("de").startsWith(name)));const outgoing=fixedExpenses+actualEntries.filter(e=>e.kind==="out").reduce((n,e)=>n+e.amount,0);const incoming=fixedEarnings+actualEntries.filter(e=>e.kind==="in").reduce((n,e)=>n+e.amount,0);const balance=incoming-outgoing;
 function navigateApp(path:string){const ingress=window.location.pathname.match(/^(\/api\/hassio_ingress\/[A-Za-z0-9_-]+)/);if(ingress){window.location.assign(`${ingress[1]}${path}`);return}router.push(path)}
 function followDebtLink(event:React.MouseEvent<HTMLAnchorElement>){event.preventDefault();navigateApp("/finanzen?tab=ausgleich")}
 return <div className="page-stack dashboard-page"><PageHeading eyebrow="Euer WG-Alltag" title="Guten Tag, Marcel 👋" subtitle="Die wichtigsten Dinge für zuhause. Schnell eintragen, weitergehen." action={<span className="live-pill"><i/>Gemeinsam synchronisiert</span>}/>
  <div className="stats-grid four"><Stat icon={<Wallet size={17}/>} label="Wohnungskonto" value={entriesReady?eur(balance):"…"} sub="Monatssaldo ab 0 € · Fixposten eingerechnet" link="/finanzen"/><Stat icon={<ArrowUpRight size={17}/>} label="Schuldenstand" value={debtsReady?eur(Math.abs(net)):"…"} sub={debtsReady?(net>0?"Philip schuldet Marcel":net<0?"Marcel schuldet Philip":"Ausgeglichen"):"Wird synchronisiert"} positive={net>0} link="/finanzen?tab=ausgleich" onClick={followDebtLink}/><Stat icon={<Clock3 size={17}/>} label="Ausgaben diesen Monat" value={entriesReady?eur(outgoing):"…"} sub={`${eur(incoming)} Geld rein`} link="/finanzen?tab=Budget%20Analyse"/><Stat icon={<ShoppingBasket size={17}/>} label="Einkaufsliste" value={`${openItems} offen`} sub={`${items.length} Artikel gesamt`} link="/einkauf"/></div>
  <Panel className="shortcut-panel"><div className="panel-heading"><SectionTitle title="Schnellaktionen" description="Ein Tipp öffnet die passende Eingabe"/></div><div className="shortcut-row">{quick.map(s=><button className="shortcut" key={s.label} onClick={()=>router.push(s.label==="Einkauf"?"/einkauf":"/finanzen?aktion="+encodeURIComponent(s.label))}><span className={`shortcut-icon ${s.tone}`}>{s.icon}</span><span>{s.label}</span><ChevronRight size={14}/></button>)}</div></Panel>
  <div className="content-grid dashboard-grid"><div className="main-column dashboard-logs"><Panel><div className="panel-heading"><SectionTitle title="Letzte Bewegungen" description="Haushaltskonto · Ausgänge gehen immer vom Wohnungskonto"/><Link className="text-button" href="/finanzen">Alle Buchungen <ChevronRight size={14}/></Link></div><div className="transaction-list">{entries.slice(0,5).map(e=><div className={`transaction ${e.purchase?"purchase-entry":""}`} key={e.id} onClick={()=>{if(e.purchase)setPurchaseLog({title:e.title,amount:e.amount,date:e.date,purchase:e.purchase})}} role={e.purchase?"button":undefined} tabIndex={e.purchase?0:undefined} onKeyDown={event=>{if(e.purchase&&(event.key==="Enter"||event.key===" "))setPurchaseLog({title:e.title,amount:e.amount,date:e.date,purchase:e.purchase})}}><span className={`transaction-icon ${e.kind==="in"?"green":"orange"}`}>{e.kind==="in"?<ArrowDownLeft size={17}/>:<ArrowUpRight size={17}/>}</span><div className="transaction-main"><b>{e.title}</b><small>{e.kind==="in"?`Von ${e.recipient}`:`An ${e.recipient}`} · {e.date}{e.purchase?" · Einkaufsdetails":""}</small></div><strong className={`amount ${e.kind==="in"?"in-amount":"out-amount"}`}>{e.kind==="in"?"+":"−"}{eur(e.amount)}</strong></div>)}</div>{entries.length===0&&<p className="quiet-note">Noch keine Buchungen. Über „Geld raus“ oder „Geld rein“ starten.</p>}</Panel><Panel><div className="panel-heading"><SectionTitle title="Letzte Schulden" description="Neue Schulden und Rückzahlungen"/><Link className="text-button" href="/finanzen?tab=ausgleich">Alle Schulden <ChevronRight size={14}/></Link></div><div className="transaction-list">{debts.slice(0,5).map(debt=><div className={`transaction ${debt.purchase?"purchase-entry":""}`} key={debt.id} onClick={()=>{if(debt.purchase)setPurchaseLog({title:debt.purpose,amount:debt.amount,date:debt.date,purchase:debt.purchase})}} role={debt.purchase?"button":undefined} tabIndex={debt.purchase?0:undefined} onKeyDown={event=>{if(debt.purchase&&(event.key==="Enter"||event.key===" "))setPurchaseLog({title:debt.purpose,amount:debt.amount,date:debt.date,purchase:debt.purchase})}}><span className={`transaction-icon ${debt.direction==="repayment"?"green":"orange"}`}>{debt.direction==="repayment"?<ArrowDownLeft size={17}/>:<ArrowUpRight size={17}/>}</span><div className="transaction-main"><b>{debt.purpose|| (debt.direction==="repayment"?"Rückzahlung":"Schuld")}</b><small>{debt.from} → {debt.to} · {debt.date}{debt.method?` · ${debt.method}`:""}{debt.purchase?" · Einkaufsdetails":""}</small></div><strong className={`amount ${debt.direction==="repayment"?"in-amount":"out-amount"}`}>{debt.direction==="repayment"?"−":"+"}{eur(debt.amount)}</strong></div>)}</div>{debts.length===0&&<p className="quiet-note">Noch keine Schulden oder Rückzahlungen.</p>}</Panel></div></div>
  <PurchaseLogDialog record={purchaseLog} onClose={()=>setPurchaseLog(null)} layout={preferences.shoppingLayout??"tiles"}/>
 </div>
}
function Stat({icon,label,value,sub,positive,link,onClick}:{icon:React.ReactNode;label:string;value:string;sub:string;positive?:boolean;link:string;onClick?:(event:React.MouseEvent<HTMLAnchorElement>)=>void}){return <Link href={link} onClick={onClick} className="panel stat-card" aria-label={`${label}: ${value}. Öffnen`}><div className="stat-top"><span className="stat-icon">{icon}</span><span>{label}</span></div><strong>{value}</strong><small className={positive?"positive":""}>{sub}</small><ChevronRight className="stat-card-arrow" size={15}/></Link>}

