"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Download, FileUp, LockKeyhole, Plus, Save, Trash2, X } from "lucide-react";
import { PageHeading, Panel, SectionTitle } from "@/components/ui";
import { costSummary, sumCosts, refundFor, sumRefunds, newCostId, isSavingRow, type CostPlan, type CostRow } from "@/domain/cost-plan";
import "./kostenrechnung.css";
import { StatementImport } from "./statement-import";
type Group="income"|"fixed"|"expenses"|"closing"|"adjustments"|"monthlyIncome"|"monthlyFixed";
const euro=(amount:number)=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(amount);
const api="/api/kostenrechnung";
export default function Kostenrechnung() {
 const [token,setToken]=useState(""),[pin,setPin]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [plan,setPlan]=useState<CostPlan|null>(null),[revision,setRevision]=useState(""),[dirty,setDirty]=useState(false),[saved,setSaved]=useState("");
 const [tab,setTab]=useState<"Monat"|"Fixkosten"|"Abschluss">("Monat"),[month,setMonth]=useState("2026-09");
 const [showImport,setShowImport]=useState(false),[imported,setImported]=useState("");
 const [includeSavings,setIncludeSavings]=useState(true);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(!token)dialog.current?.showModal();else dialog.current?.close()},[token]);
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=""};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 async function load(access:string) {
  const response=await fetch(api,{headers:{Authorization:"Bearer "+access},cache:"no-store"});
  const data=await response.json();if(!response.ok)throw new Error(data.error||"Laden fehlgeschlagen.");
  setPlan(data.plan);setRevision(data.revision);setDirty(false);setSaved("");
 }
 async function unlock(event:React.FormEvent) {
  event.preventDefault();setBusy(true);setError("");
  try{const response=await fetch(api+"/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pin})});const data=await response.json();if(!response.ok)throw new Error(data.error);await load(data.token);setToken(data.token);setPin("")}catch(err){setError(err instanceof Error?err.message:"Verbindung fehlgeschlagen.")}finally{setBusy(false)}
 }
 async function save() {
  setBusy(true);setError("");
  try{const response=await fetch(api,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({plan,revision})});const data=await response.json();if(!response.ok)throw new Error(data.error);setRevision(data.revision);setDirty(false);setSaved("Gespeichert");setImported("")}catch(err){setError(err instanceof Error?err.message:"Speichern fehlgeschlagen.")}finally{setBusy(false)}
 }
 function change(group:Group,id:string,patch:Partial<CostRow>){setPlan(current=>current?{...current,[group]:(current[group]||[]).map(row=>row.id===id?{...row,...patch}:row)}:current);setDirty(true);setSaved("")}
 function add(group:Group){setPlan(current=>current?{...current,[group]:[...(current[group]||[]),{id:newCostId(),name:"",amount:0,refund:0,note:"",month}]}:current);setDirty(true);setSaved("")}
 function remove(group:Group,id:string){setPlan(current=>current?{...current,[group]:(current[group]||[]).filter(row=>row.id!==id)}:current);setDirty(true);setSaved("")}
 function exportCsv(){
  if(!plan)return;
  const escape=(value:unknown)=>'"'+String(value).replace(/"/g,'""')+'"';
  const records=[["Bereich","Monat","Bezeichnung","Betrag EUR","Rückzahlung / Gutschrift EUR","Notiz"]];
  for(const group of ["income","fixed","expenses","closing","adjustments","monthlyIncome","monthlyFixed"] as Group[])for(const row of plan[group]||[])records.push([({income:"Einnahmen (Plan)",fixed:"Fixkosten (Plan)",expenses:"Ausgaben",closing:"Abschluss",adjustments:"Nachzahlungen",monthlyIncome:"Einnahmen (PDF)",monthlyFixed:"Fixkosten (PDF)"})[group],["expenses","monthlyIncome","monthlyFixed"].includes(group)?row.month:"",row.name,row.amount.toFixed(2).replace(".",","),refundFor(row).toFixed(2).replace(".",","),row.note]);
  records.push(["Kontostand","","",plan.closingBalance.toFixed(2).replace(".",","),"",""]);
  const url=URL.createObjectURL(new Blob(["\uFEFF"+records.map(row=>row.map(escape).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="Kostenrechnung.csv";link.click();URL.revokeObjectURL(url);
 }
 function rows(group:Group,title:string,refunds=false,allBookings=false) {
  if(!plan)return null;
  const groups:Group[]=allBookings?(plan.actualMonths?.includes(month)?["monthlyIncome","monthlyFixed","expenses"]:["income","fixed","expenses"]):[group];
  const all=groups.flatMap(rowGroup=>(plan[rowGroup]||[]).filter(row=>!["expenses","monthlyFixed","monthlyIncome"].includes(rowGroup)||row.month===month).map(row=>({...row,rowGroup})));
  const list=all.filter(row=>!allBookings||includeSavings||["income","monthlyIncome","closing","adjustments"].includes(row.rowGroup)||!isSavingRow(row));
  const groupLabel=(value:Group)=>["income","monthlyIncome"].includes(value)?"Einnahme":["fixed","monthlyFixed"].includes(value)?"Fixkosten":"Einmalige Ausgabe";
  const total=allBookings?list.reduce((sum,row)=>sum+(["income","monthlyIncome"].includes(row.rowGroup)?row.amount:-row.amount),0):sumCosts(list);
  return <Panel className="cost-panel"><div className="panel-heading"><SectionTitle title={title} description={allBookings?`${list.length} Buchungen${all.length>list.length?` · ${all.length-list.length} Sparposten ausgeblendet`:""} · Summen aktualisieren sich sofort`:undefined}/><button className="button" onClick={()=>add(group)} disabled={busy}><Plus size={15}/>Posten hinzufügen</button></div>
   <div className="cost-table-scroll"><table className={`cost-table ${refunds?"cost-table-refunds":""}`}><thead><tr><th>Bezeichnung</th><th>Betrag €</th>{refunds&&<th>Rückzahlung / Gutschrift €</th>}<th>Notiz</th><th><span className="cost-sr-only">Aktionen</span></th></tr></thead><tbody>
   {list.map(row=>{const group=row.rowGroup;return <tr key={`${group}-${row.id}`}><td data-label="Bezeichnung"><input disabled={busy} aria-label="Bezeichnung" maxLength={300} placeholder="Neuer Posten" value={row.name} onChange={event=>change(group,row.id,{name:event.target.value})}/>{(allBookings||row.date)&&<small className="cost-row-date">{allBookings&&groupLabel(group)}{allBookings&&row.date&&" · "}{row.date?.split("-").reverse().join(".")}</small>}{["expenses","fixed","monthlyFixed"].includes(group)&&<label className="cost-saving-check"><input type="checkbox" aria-label={"Sparen: "+(row.name||"Neuer Posten")} checked={isSavingRow(row)} disabled={busy} onChange={event=>change(group,row.id,{isSaving:event.target.checked})}/>Sparen</label>}</td><td data-label="Betrag €"><Amount value={row.amount} disabled={busy} label={"Betrag "+(row.name||"neuer Posten")} onChange={amount=>change(group,row.id,{amount})}/></td>{refunds&&<td data-label="Rückzahlung €"><select className="cost-refund-mode" disabled={busy} aria-label={"Rückzahlungsregel "+row.name} value={row.refundMode||"manual"} onChange={event=>change(group,row.id,{refundMode:event.target.value as CostRow["refundMode"],refund:refundFor(row)})}><option value="manual">Manuell</option><option value="half">Halber Betrag</option><option value="full">Ganzer Betrag</option></select><Amount value={refundFor(row)} disabled={busy||row.refundMode==="half"||row.refundMode==="full"} label={"Rückzahlung "+row.name} onChange={refund=>change(group,row.id,{refund})}/></td>}<td data-label="Notiz"><input disabled={busy} aria-label={"Notiz "+row.name} maxLength={2000} placeholder="Optional" value={row.note} onChange={event=>change(group,row.id,{note:event.target.value})}/></td><td className="cost-row-action"><button disabled={busy} className="cost-delete" aria-label={(row.name||"Posten")+" löschen"} onClick={()=>remove(group,row.id)}><Trash2 size={16}/></button></td></tr>})}
   {!list.length&&<tr><td colSpan={refunds?5:4} className="cost-empty">Noch keine Posten. Füge deinen ersten Eintrag hinzu.</td></tr>}
   </tbody><tfoot><tr><th>{allBookings?"Monatssaldo":"Gesamt"}</th><td>{euro(total)}</td>{refunds&&<td>{euro(sumRefunds(list))}</td>}<td colSpan={2}/></tr></tfoot></table></div></Panel>
 }
 const summary=plan?costSummary(plan,month,includeSavings):null;
 const actual=Boolean(plan?.actualMonths?.includes(month));
 return <div className="cost-page"><PageHeading eyebrow="PERSÖNLICH" title="Kostenrechnung" subtitle="Deine Kosten, einfach im Blick." action={token&&<div className="cost-actions"><button className="button" disabled={busy} onClick={()=>setShowImport(true)}><FileUp size={15}/>PDF importieren</button><button className="button" disabled={busy} onClick={exportCsv}><Download size={15}/>Excel-Export (CSV)</button><button className="button primary" disabled={busy||!dirty} onClick={save}><Save size={15}/>{busy?"Speichert …":"Speichern"}</button><button className="button" disabled={busy} onClick={()=>{if(dirty&&!window.confirm("Ungespeicherte Änderungen verwerfen und sperren?"))return;void fetch(api+"/session",{method:"DELETE",headers:{Authorization:"Bearer "+token}});setToken("");setPlan(null);setDirty(false);setError("");setSaved("");setImported("")}}><LockKeyhole size={15}/>Sperren</button></div>}/>
  {!token&&<Panel className="cost-locked"><LockKeyhole size={28}/><h2>Geschützter Bereich</h2><p>Zum Öffnen bitte deinen PIN eingeben.</p></Panel>}
  <dialog ref={dialog} className="cost-pin-dialog" aria-labelledby="cost-pin-title" onCancel={event=>{event.preventDefault();const ingress=window.location.pathname.match(/^(\/api\/hassio_ingress\/[A-Za-z0-9_-]+)/);window.location.assign(ingress?ingress[1]+"/":"/");}}>
   <form onSubmit={unlock}><div className="cost-pin-head"><LockKeyhole size={24}/><Link href="/" aria-label="Zurück zum Dashboard"><X size={20}/></Link></div><h2 id="cost-pin-title">Kostenrechnung entsperren</h2><p>Gib deinen vierstelligen PIN ein.</p><label htmlFor="cost-pin">PIN</label><input id="cost-pin" autoFocus type="password" inputMode="numeric" autoComplete="off" pattern="[0-9]{4}" maxLength={4} value={pin} onChange={event=>setPin(event.target.value.replace(/\D/g,""))} required disabled={busy}/>{error&&<p className="cost-error" role="alert">{error}</p>}<button className="button primary" disabled={busy||pin.length!==4}>{busy?"Öffnet …":"Entsperren"}</button><Link className="cost-cancel" href="/">Abbrechen</Link></form>
  </dialog>
  {token&&plan&&summary&&<><div className="cost-status" role="status"><b>{dirty?"Ungespeicherte Änderungen":saved||"Geladen"}</b><span>{actual?"PDF-Buchungen für diesen Monat":"Plan aus deiner Excel-Datei"}</span></div>{imported&&<p className="cost-note" role="status">{imported}</p>}{error&&<div className="cost-error" role="alert">{error}<button className="button" disabled={busy} onClick={async()=>{if(dirty&&!window.confirm("Änderungen verwerfen und gespeicherten Stand laden?"))return;setBusy(true);try{await load(token);setError("")}catch(err){setError(err instanceof Error?err.message:"Laden fehlgeschlagen.")}finally{setBusy(false)}}}>Gespeicherten Stand laden</button></div>}
   <div className="cost-tabs" role="tablist" aria-label="Kostenbereiche">{(["Monat","Fixkosten","Abschluss"] as const).map(value=><button key={value} role="tab" aria-selected={tab===value} onClick={()=>setTab(value)}>{value==="Monat"?"Monatsausgaben":value==="Fixkosten"?"Fixkosten & Gehalt":"Abschlussrechnung"}</button>)}</div>
   {tab==="Monat"&&<><Panel className="cost-panel"><div className="panel-heading"><SectionTitle title="Monatsübersicht"/><label className="cost-month">Monat<input type="month" value={month} onChange={event=>{if(event.target.value)setMonth(event.target.value)}}/></label></div><label className="cost-saving-toggle"><input type="checkbox" checked={includeSavings} onChange={event=>setIncludeSavings(event.target.checked)}/>Sparposten anzeigen und einrechnen</label><div className="cost-stats cost-stats-savings"><Stat label="Gesamtkosten inkl. Sparen" value={summary.totalOut}/><Stat label="Davon Sparen" value={summary.savings}/><Stat label="Kosten ohne Sparen" value={summary.costsWithoutSavings}/><Stat label={includeSavings?"Verbleibend":"Verfügbar ohne Sparen"} value={summary.remaining} balance/></div></Panel>{rows("expenses","Buchungen im Monat",true,true)}<p className="cost-note">{!includeSavings&&"Sparposten sind ausgeblendet und werden vom verfügbaren Betrag nicht abgezogen. "}Rückzahlungen / Gutschriften: {euro(summary.refunds)}. Diese Merkposten werden wie in deiner Excel-Datei nicht automatisch vom Ausgabenbetrag abgezogen.</p></>}
   {tab==="Fixkosten"&&<><Panel className="cost-panel"><div className="panel-heading"><SectionTitle title={actual?"Einnahmen & Fixkosten im Monat":"Monatliche Planung"}/><label className="cost-month">Monat<input type="month" value={month} onChange={event=>{if(event.target.value)setMonth(event.target.value)}}/></label></div><div className="cost-stats"><Stat label="Monatliche Einnahmen" value={summary.income}/><Stat label="Fixkosten gesamt" value={summary.fixed}/><Stat label="Rest nach Fixkosten" value={summary.available} balance/></div></Panel>{rows(actual?"monthlyIncome":"income","Gehalt & Einnahmen")}{rows(actual?"monthlyFixed":"fixed","Monatliche Fixkosten")}<p className="cost-note">{actual?"Für diesen Monat zählen die importierten Einnahmen und Fixkosten. Die allgemeinen Planwerte bleiben für andere Monate erhalten.":"Gehalt und Fixkosten bilden wie in deiner Excel-Datei die gemeinsame Basis aller Monate ohne PDF-Import."}</p></>}
   {tab==="Abschluss"&&<><Panel className="cost-panel"><div className="panel-heading"><SectionTitle title="Kontostand nach Abschluss Sparkasse"/><label className="cost-month">Kontostand €<Amount label="Kontostand" value={plan.closingBalance} signed disabled={busy} onChange={closingBalance=>{setPlan({...plan,closingBalance});setDirty(true);setSaved("")}}/></label></div><div className="cost-stats"><Stat label="Ausgaben gesamt" value={summary.closingExpenses}/><Stat label="Rest" value={summary.closingRemaining}/><Stat label="Nach Auto-Nachzahlung" value={summary.afterAdjustments} balance/></div></Panel>{rows("closing","Ausgaben aus Tabelle4")}{rows("adjustments","Nachzahlungen")}<p className="cost-note">Die Abschlussrechnung ist eine separate Rechnung aus „Tabelle4“. Unbenannte Posten kannst du hier benennen.</p></>}
   {showImport&&<StatementImport plan={plan} onClose={()=>setShowImport(false)} onImport={(next,importMonth,count)=>{setPlan(next);if(importMonth)setMonth(importMonth);setTab("Monat");setDirty(true);setSaved("");setImported(`${count} Buchungen übernommen. Bitte speichern, damit sie auch auf anderen Geräten verfügbar sind.`);setShowImport(false)}}/>}
  </>}
 </div>
}
function Stat({label,value,balance=false}:{label:string;value:number;balance?:boolean}){return <div><small>{label}</small><b className={balance?(value<0?"cost-negative":"cost-positive"):""}>{euro(value)}</b></div>}
function Amount({value,onChange,label,disabled,signed=false}:{value:number;onChange:(amount:number)=>void;label:string;disabled:boolean;signed?:boolean}){
 const [text,setText]=useState(value.toFixed(2).replace(".",","));
 useEffect(()=>setText(value.toFixed(2).replace(".",",")),[value]);
 return <input aria-label={label} inputMode="decimal" disabled={disabled} value={text} onChange={event=>setText(event.target.value)} onBlur={()=>{const normalized=text.trim().replace(",",".");const parsed=Number(normalized);if(normalized!==""&&Number.isFinite(parsed)&&(signed||parsed>=0)&&Math.abs(parsed)<=1e9){const rounded=Math.round(parsed*100)/100;onChange(rounded);setText(rounded.toFixed(2).replace(".",","))}else setText(value.toFixed(2).replace(".",","))}} onKeyDown={event=>{if(event.key==="Enter")event.currentTarget.blur()}}/>
}
