"use client";
import { useEffect, useRef, useState } from "react";
import { Download, FileUp, LockKeyhole, Plus, Save, Trash2, X } from "lucide-react";
import { PageHeading, Panel, SectionTitle } from "@/components/ui";
import { costSummary, sumCosts, refundFor, sumRefunds, newCostId, isSavingRow,updateCostRegulars,currentCostMonth,nextCostMonth,type CostPlan, type CostRow } from "@/domain/cost-plan";
import "./kostenrechnung.css";
import {costSuggestions,savingsSource} from "@/domain/cost-suggestions";
import { StatementImport } from "./statement-import";
type Group="income"|"fixed"|"expenses"|"closing"|"adjustments"|"monthlyIncome"|"monthlyFixed";
const euro=(amount:number)=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(amount);
const api="/api/kostenrechnung";
export default function Kostenrechnung() {
 const [token,setToken]=useState(""),[pin,setPin]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [plan,setPlan]=useState<CostPlan|null>(null),[revision,setRevision]=useState(""),[dirty,setDirty]=useState(false),[saved,setSaved]=useState("");
 const [tab,setTab]=useState<"Monat"|"Fixkosten"|"Gegenrechnung"|"Vorgeschlagen">("Monat"),[month,setMonth]=useState(currentCostMonth());
 const [showImport,setShowImport]=useState(false),[imported,setImported]=useState("");
 const [showClear,setShowClear]=useState(false),[clearScope,setClearScope]=useState<"month"|"all">("month"),[clearPin,setClearPin]=useState(""),[clearError,setClearError]=useState(""),[clearing,setClearing]=useState(false);
 const clearDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(showClear)clearDialog.current?.showModal();else clearDialog.current?.close()},[showClear]);
 const [applyCurrent,setApplyCurrent]=useState(false);
 const todayMonth=currentCostMonth();
 const [bookingFilter,setBookingFilter]=useState<"all"|"in"|"out">("all"),[scenario,setScenario]=useState(10);
 const [includeSavings,setIncludeSavings]=useState(true);
 const [ingressBase,setIngressBase]=useState("");
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{setIngressBase(window.location.pathname.match(/^(\/api\/hassio_ingress\/[A-Za-z0-9_-]+)/)?.[1]||"")},[]);
 function goHome(event?:React.MouseEvent<HTMLAnchorElement>){event?.preventDefault();const base=window.location.pathname.match(/^(\/api\/hassio_ingress\/[A-Za-z0-9_-]+)/)?.[1]||"";window.location.assign(`${base}/`)}
 useEffect(()=>{if(!token)dialog.current?.showModal();else dialog.current?.close()},[token]);
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=""};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 async function load(access:string) {
  const response=await fetch(api,{headers:{Authorization:"Bearer "+access},cache:"no-store"});
  const data=await response.json();if(!response.ok)throw new Error(data.error||"Laden fehlgeschlagen.");
  setPlan(data.plan);setRevision(data.revision);setDirty(false);setSaved("");
 }
 async function unlock(event:React.FormEvent) {
  event.preventDefault();setBusy(true);setError("");
  try{const response=await fetch(api+"/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pin})});const data=await response.json();if(!response.ok)throw new Error(data.error);await load(data.token);setToken(data.token);setPin("")}catch(err){setError(err instanceof Error?err.message:"Verbindung fehlgeschlagen.")}finally{setBusy(false)}
 }
 async function save() {
  setBusy(true);setError("");
  try{const response=await fetch(api,{method:"PUT",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({plan,revision})});const data=await response.json();if(!response.ok)throw new Error(data.error);setRevision(data.revision);setDirty(false);setSaved("Gespeichert");setImported("")}catch(err){setError(err instanceof Error?err.message:"Speichern fehlgeschlagen.")}finally{setBusy(false)}
 }
 async function clearRows(event:React.FormEvent){
  event.preventDefault();if(!plan)return;setClearing(true);setClearError("");
  try{const response=await fetch(api,{method:"DELETE",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({pin:clearPin,scope:clearScope,month,plan,revision})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Löschen fehlgeschlagen.");setPlan(data.plan);setRevision(data.revision);setDirty(false);setImported("");setSaved(clearScope==="all"?"Kostenrechnung zurückgesetzt":"Monatsbuchungen gelöscht");setShowClear(false);setClearPin("")}
  catch(error){setClearError(error instanceof Error?error.message:"Löschen fehlgeschlagen.")}finally{setClearing(false)}
 }
 function change(group:Group,id:string,patch:Partial<CostRow>){setPlan(current=>{if(!current)return current;const updated=(current[group]||[]).map(row=>row.id===id?{...row,...patch}:row);if(JSON.stringify(updated)===JSON.stringify(current[group]))return current;return group==="income"||group==="fixed"?updateCostRegulars(current,group,updated,applyCurrent,todayMonth):{...current,[group]:updated}});setDirty(true);setSaved("")}
 function add(group:Group){setPlan(current=>{if(!current)return current;const updated=[...(current[group]||[]),{id:newCostId(),name:"",amount:0,refund:0,note:"",month,...(group==="expenses"?{kind:bookingFilter==="in"?"in" as const:"out" as const}:{})}];return group==="income"||group==="fixed"?updateCostRegulars(current,group,updated,applyCurrent,todayMonth):{...current,[group]:updated}});setDirty(true);setSaved("")}
 function remove(group:Group,id:string){setPlan(current=>{if(!current)return current;const updated=(current[group]||[]).filter(row=>row.id!==id);return group==="income"||group==="fixed"?updateCostRegulars(current,group,updated,applyCurrent,todayMonth):{...current,[group]:updated}});setDirty(true);setSaved("")}
 function exportCsv(){
  if(!plan)return;
  const escape=(value:unknown)=>'"'+String(value).replace(/"/g,'""')+'"';
  const records=[["Bereich","Monat","Bezeichnung","Betrag EUR","Rückzahlung / Gutschrift EUR","Notiz"]];
  for(const group of ["income","fixed","expenses","closing","adjustments","monthlyIncome","monthlyFixed"] as Group[])for(const row of plan[group]||[])records.push([({income:"Einnahmen (Plan)",fixed:"Fixkosten (Plan)",expenses:row.kind==="in"?"Monatseinnahmen":"Monatsausgaben",closing:"Gegenrechnung",adjustments:"Nachzahlungen",monthlyIncome:"Einnahmen (PDF)",monthlyFixed:"Fixkosten (PDF)"})[group],["expenses","monthlyIncome","monthlyFixed"].includes(group)?row.month:"",row.name,row.amount.toFixed(2).replace(".",","),refundFor(row).toFixed(2).replace(".",","),row.note]);
  records.push(["Kontostand","","",plan.closingBalance.toFixed(2).replace(".",","),"",""]);
  const url=URL.createObjectURL(new Blob(["\uFEFF"+records.map(row=>row.map(escape).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="Kostenrechnung.csv";link.click();URL.revokeObjectURL(url);
 }
 function rows(group:Group,title:string,refunds=false,allBookings=false) {
  if(!plan)return null;
  const groups:Group[]=allBookings?["expenses"]:[group];
  const all=groups.flatMap(rowGroup=>(plan[rowGroup]||[]).filter(row=>!["expenses","monthlyFixed","monthlyIncome"].includes(rowGroup)||row.month===month).map(row=>({...row,rowGroup})));
  const incoming=(row:CostRow&{rowGroup:Group})=>["income","monthlyIncome"].includes(row.rowGroup)||row.rowGroup==="expenses"&&row.kind==="in";
  const list=all.filter(row=>!allBookings||((bookingFilter==="all"||(incoming(row)?"in":"out")===bookingFilter)&&(includeSavings||incoming(row)||!isSavingRow(row))));
  const groupLabel=(value:Group)=>["income","monthlyIncome"].includes(value)?"Einnahme":["fixed","monthlyFixed"].includes(value)?"Fixkosten":"Einmalige Ausgabe";
  const total=allBookings?list.reduce((sum,row)=>sum+(incoming(row)?row.amount:-row.amount),0):sumCosts(list);
  return <Panel className="cost-panel"><div className="panel-heading"><SectionTitle title={title} description={allBookings?`${list.length} zusätzliche Monatsbuchungen${all.length>list.length?` · ${all.length-list.length} Sparposten ausgeblendet`:""} · Summen aktualisieren sich sofort`:undefined}/><button className="button" onClick={()=>add(group)} disabled={busy}><Plus size={15}/>{allBookings?(bookingFilter==="in"?"Einnahme hinzufügen":bookingFilter==="out"?"Ausgabe hinzufügen":"Posten hinzufügen"):"Posten hinzufügen"}</button></div>
   <div className="cost-table-scroll"><table className={`cost-table ${refunds?"cost-table-refunds":""}`}><thead><tr><th>Bezeichnung</th><th>Betrag €</th>{refunds&&<th>Rückzahlung / Gutschrift €</th>}<th>Notiz</th><th><span className="cost-sr-only">Aktionen</span></th></tr></thead><tbody>
   {list.map(row=>{const group=row.rowGroup;return <tr key={`${group}-${row.id}`}><td data-label="Bezeichnung"><input disabled={busy} aria-label="Bezeichnung" maxLength={300} placeholder="Neuer Posten" value={row.name} onChange={event=>change(group,row.id,{name:event.target.value})}/>{(allBookings||row.date)&&<small className="cost-row-date">{allBookings&&(incoming(row)?"Einnahme":groupLabel(group))}{allBookings&&row.date&&" · "}{row.date?.split("-").reverse().join(".")}</small>}{["expenses","fixed","monthlyFixed"].includes(group)&&!incoming(row)&&<label className="cost-saving-check"><input type="checkbox" aria-label={"Sparen: "+(row.name||"Neuer Posten")} checked={isSavingRow(row)} disabled={busy} onChange={event=>change(group,row.id,{isSaving:event.target.checked})}/>Sparen</label>}</td><td data-label="Betrag €">{group==="expenses"&&<select className="cost-refund-mode" aria-label={"Art "+(row.name||"Neuer Posten")} disabled={busy} value={row.kind||"out"} onChange={event=>change(group,row.id,{kind:event.target.value as "in"|"out"})}><option value="out">Ausgabe</option><option value="in">Einnahme</option></select>}<Amount value={row.amount} disabled={busy} label={"Betrag "+(row.name||"neuer Posten")} onChange={amount=>change(group,row.id,{amount})}/></td>{refunds&&<td data-label="Rückzahlung €"><select className="cost-refund-mode" disabled={busy} aria-label={"Rückzahlungsregel "+row.name} value={row.refundMode||"manual"} onChange={event=>change(group,row.id,{refundMode:event.target.value as CostRow["refundMode"],refund:refundFor(row)})}><option value="manual">Manuell</option><option value="half">Halber Betrag</option><option value="full">Ganzer Betrag</option></select><Amount value={refundFor(row)} disabled={busy||row.refundMode==="half"||row.refundMode==="full"} label={"Rückzahlung "+row.name} onChange={refund=>change(group,row.id,{refund})}/></td>}<td data-label="Notiz"><input disabled={busy} aria-label={"Notiz "+row.name} maxLength={2000} placeholder="Optional" value={row.note} onChange={event=>change(group,row.id,{note:event.target.value})}/></td><td className="cost-row-action"><button disabled={busy} className="cost-delete" aria-label={(row.name||"Posten")+" löschen"} onClick={()=>remove(group,row.id)}><Trash2 size={16}/></button></td></tr>})}
   {!list.length&&<tr><td colSpan={refunds?5:4} className="cost-empty">Noch keine Posten. Füge deinen ersten Eintrag hinzu.</td></tr>}
   </tbody><tfoot><tr><th>{allBookings?"Summe Monatsbuchungen":"Gesamt"}</th><td>{euro(total)}</td>{refunds&&<td>{euro(sumRefunds(list))}</td>}<td colSpan={2}/></tr></tfoot></table></div></Panel>
 }
 const summary=plan?costSummary(plan,month,includeSavings):null;
 const check=plan?.checks?.[month]||{opening:0,income:0,expenses:0};
 const suggested=plan?costSuggestions(plan,month,scenario):null;
 const actual=Boolean(plan?.actualMonths?.includes(month));
 return <div className="cost-page"><PageHeading eyebrow="PERSÖNLICH" title="Kostenrechnung" subtitle="Deine Kosten, einfach im Blick." action={token&&<div className="cost-actions"><button className="button cost-clear-button" disabled={busy} onClick={()=>{setClearPin("");setClearError("");setClearScope("month");setShowClear(true)}}><Trash2 size={15}/>Alle Zeilen löschen</button><button className="button" disabled={busy} onClick={()=>setShowImport(true)}><FileUp size={15}/>PDF importieren</button><button className="button" disabled={busy} onClick={exportCsv}><Download size={15}/>Excel-Export (CSV)</button><button className="button primary" disabled={busy||!dirty} onClick={save}><Save size={15}/>{busy?"Speichert …":"Speichern"}</button><button className="button" disabled={busy} onClick={()=>{if(dirty&&!window.confirm("Ungespeicherte Änderungen verwerfen und sperren?"))return;void fetch(api+"/session",{method:"DELETE",headers:{Authorization:"Bearer "+token}});setToken("");setPlan(null);setDirty(false);setError("");setSaved("");setImported("")}}><LockKeyhole size={15}/>Sperren</button></div>}/>
  {!token&&<Panel className="cost-locked"><LockKeyhole size={28}/><h2>Geschützter Bereich</h2><p>Zum Öffnen bitte deinen PIN eingeben.</p></Panel>}
  <dialog ref={dialog} className="cost-pin-dialog" aria-labelledby="cost-pin-title" onCancel={event=>{event.preventDefault();goHome()}}>
   <form onSubmit={unlock}><div className="cost-pin-head"><LockKeyhole size={24}/><a href={`${ingressBase}/`} onClick={goHome} aria-label="Zurück zum Dashboard"><X size={20}/></a></div><h2 id="cost-pin-title">Kostenrechnung entsperren</h2><p>Gib deinen vierstelligen PIN ein.</p><label htmlFor="cost-pin">PIN</label><input id="cost-pin" autoFocus type="password" inputMode="numeric" autoComplete="off" pattern="[0-9]{4}" maxLength={4} value={pin} onChange={event=>setPin(event.target.value.replace(/\D/g,""))} required disabled={busy}/>{error&&<p className="cost-error" role="alert">{error}</p>}<button className="button primary" disabled={busy||pin.length!==4}>{busy?"Öffnet …":"Entsperren"}</button><a className="cost-cancel" href={`${ingressBase}/`} onClick={goHome}>Abbrechen</a></form>
  </dialog>
  {token&&plan&&summary&&<><div className="cost-status" role="status"><b>{dirty?"Ungespeicherte Änderungen":saved||"Geladen"}</b><span>{actual?"PDF-Buchungen für diesen Monat":"Plan aus deiner Excel-Datei"}</span></div>{imported&&<p className="cost-note" role="status">{imported}</p>}{error&&<div className="cost-error" role="alert">{error}<button className="button" disabled={busy} onClick={async()=>{if(dirty&&!window.confirm("Änderungen verwerfen und gespeicherten Stand laden?"))return;setBusy(true);try{await load(token);setError("")}catch(err){setError(err instanceof Error?err.message:"Laden fehlgeschlagen.")}finally{setBusy(false)}}}>Gespeicherten Stand laden</button></div>}
   <div className="cost-tabs" role="tablist" aria-label="Kostenbereiche">{(["Monat","Fixkosten","Gegenrechnung","Vorgeschlagen"] as const).map(value=><button key={value} role="tab" className={tab===value?"cost-tab-active":""} aria-selected={tab===value} onClick={()=>setTab(value)}>{value==="Monat"?"Monatsüberblick":value==="Fixkosten"?"Fixkosten & Gehalt":value==="Vorgeschlagen"?"Vorgeschlagen":"Gegenrechnung"}</button>)}</div>
   {tab==="Monat"&&<><Panel className="cost-panel"><div className="panel-heading"><SectionTitle title="Monatsüberblick"/><label className="cost-month">Monat<input type="month" value={month} onChange={event=>{if(event.target.value)setMonth(event.target.value)}}/></label></div><label className="cost-saving-toggle"><input type="checkbox" checked={includeSavings} onChange={event=>setIncludeSavings(event.target.checked)}/>Sparen einrechnen und Sparposten anzeigen</label><div className="cost-stats cost-stats-savings"><Stat label="Fixe Einnahmen" value={summary.fixedIncome}/><Stat label="Zusätzliche Einnahmen" value={summary.additionalIncome}/><Stat label={includeSavings?"Fixe Ausgaben mit Sparen":"Fixe Ausgaben ohne Sparen"} value={summary.displayedFixed}/><Stat label={includeSavings?"Ausgaben ohne Fixkosten · mit Sparen":"Ausgaben ohne Fixkosten · ohne Sparen"} value={summary.displayedExpenses}/><Stat label="Sparbetrag gesamt" value={summary.savings}/><Stat label={includeSavings?"Gesamtkosten mit Sparen":"Gesamtkosten ohne Sparen"} value={summary.displayedOut}/><Stat label={includeSavings?"Rest mit Sparen":"Rest ohne Sparen"} value={summary.remaining} balance/></div></Panel><div className="cost-filter" role="group" aria-label="Buchungen anzeigen">{(["all","in","out"] as const).map(value=><button key={value} className="button" aria-pressed={bookingFilter===value} onClick={()=>setBookingFilter(value)}>{value==="all"?"Alle Buchungen":value==="in"?"Einnahmen":"Ausgaben"}</button>)}</div>{rows("expenses","Buchungen im Monat",true,true)}<p className="cost-note">{!includeSavings&&"Sparposten sind ausgeblendet und werden vom verfügbaren Betrag nicht abgezogen. "}Gehalt und Fixkosten werden nur oben berechnet. Rückzahlungen / Gutschriften: {euro(summary.refunds)}. Diese Merkposten werden wie in deiner Excel-Datei nicht automatisch vom Ausgabenbetrag abgezogen.</p></>}
   {tab==="Fixkosten"&&<><Panel className="cost-panel"><div className="panel-heading"><SectionTitle title="Monatliche Planung"/><label className="cost-month">Monat<input type="month" value={month} onChange={event=>{if(event.target.value)setMonth(event.target.value)}}/></label></div><div className="cost-stats"><Stat label="Regelmäßige Einnahmen" value={sumCosts(plan.income)}/><Stat label="Fixkosten gesamt" value={sumCosts(plan.fixed)}/><Stat label="Rest nach Fixkosten" value={sumCosts(plan.income)-sumCosts(plan.fixed)} balance/></div></Panel><label className="cost-saving-toggle"><input type="checkbox" checked={applyCurrent} onChange={event=>{setApplyCurrent(event.target.checked);if(event.target.checked)setPlan(current=>current?updateCostRegulars(updateCostRegulars(current,"income",current.income,true,todayMonth),"fixed",current.fixed,true,todayMonth):current);setDirty(true);setSaved("")}}/>Bei jetzigem Monat übernehmen ({todayMonth})</label><p className="cost-note">Neue Änderungen gelten {applyCurrent?`ab ${todayMonth}`:`ab ${nextCostMonth(todayMonth)}`}. Frühere Monate behalten ihre Werte.</p>{rows("income","Gehalt & regelmäßige Einnahmen")}{rows("fixed","Monatliche Fixkosten")}<p className="cost-note">Gehalt und Fixkosten sind deine regelmäßige Planung. Der PDF-Import ändert sie nur mit aktiviertem „Fixkosten aktualisieren“; zusätzliche Einnahmen stehen im Monatsüberblick.</p></>}
   {tab==="Gegenrechnung"&&<Panel className="cost-panel"><div className="panel-heading"><SectionTitle title="Freie Gegenrechnung" description="Werte selbst eingeben und den ausgewählten Monat prüfen"/><label className="cost-month">Monat<input type="month" value={month} onChange={event=>{if(event.target.value)setMonth(event.target.value)}}/></label></div><div className="cost-check-fields">{(["opening","income","expenses"] as const).map(key=><label key={key} className="cost-month">{key==="opening"?"Startkontostand €":key==="income"?"Einnahmen €":"Ausgaben gesamt €"}<Amount label={key==="opening"?"Gegenrechnung Startkontostand":key==="income"?"Gegenrechnung Einnahmen":"Gegenrechnung Ausgaben"} value={check[key]} signed={key==="opening"} disabled={busy} onChange={value=>{setPlan({...plan,checks:{...plan.checks,[month]:{...check,[key]:value}}});setDirty(true);setSaved("")}}/></label>)}</div><div className="cost-stats"><Stat label="Errechneter Kontostand" value={check.opening+check.income-check.expenses} balance/><Stat label={includeSavings?"Monatsüberblick mit Sparen + Start":"Monatsüberblick ohne Sparen + Start"} value={check.opening+summary.remaining}/><Stat label="Differenz" value={check.income-check.expenses-summary.remaining}/></div><p className="cost-note">Diese Eingaben sind eine separate Prüfrechnung für {month}. Sie ändern keine Buchungen, kein Gehalt und keine Fixkosten. Die Differenz vergleicht Einnahmen minus Ausgaben mit dem Rest im Monatsüberblick.</p></Panel>}
   {tab==="Vorgeschlagen"&&suggested&&<><Panel className="cost-panel"><div className="panel-heading"><SectionTitle title="Wo könntest du sparen?" description="Vorschläge aus deinen Buchungen, keine automatische Änderung"/><label className="cost-month">Monat<input type="month" value={month} onChange={event=>{if(event.target.value)setMonth(event.target.value)}}/></label></div><label className="cost-scenario">Rechenbeispiel: {scenario} % weniger Ausgaben<input aria-label="Einsparung im Rechenbeispiel" type="range" min="5" max="30" step="5" value={scenario} onChange={event=>setScenario(Number(event.target.value))}/></label><p className="cost-note">Die Beträge zeigen ein mögliches Rechenbeispiel, keine garantierte Ersparnis. Sparüberweisungen und Einnahmen sind ausgeschlossen.</p></Panel><div className="cost-suggestions">{suggested.suggestions.map(item=><Panel key={item.title} className="cost-panel"><SectionTitle title={item.title}/><p>{item.tip}</p><div className="cost-stats"><Stat label="Ausgaben im gewählten Monat" value={item.amount}/><Stat label={`Bei ${scenario} % weniger`} value={item.potential}/></div><small className="cost-note">{item.count} passende Buchungen · Zuordnung anhand der Bezeichnung</small></Panel>)}</div>{!suggested.suggestions.length&&<Panel><p>Für diesen Monat sind noch keine passenden Buchungen vorhanden.</p></Panel>}<Panel className="cost-panel"><SectionTitle title="Größte Ausgaben prüfen"/>{suggested.largest.map(row=><p key={row.id}>{row.name} · {euro(row.amount)}</p>)}<p className="cost-note">Bei Fixkosten Vertragsumfang und Nutzung prüfen. Fehlende Abbuchungen allein beweisen keine Kündigung.</p><a className="text-button" href={savingsSource} target="_blank" rel="noreferrer">Grundlage: Haushaltsbuch und Ausgabenprüfung · Verbraucherzentrale</a></Panel></>}
   <dialog ref={clearDialog} className="cost-pin-dialog" aria-labelledby="cost-clear-title" onCancel={event=>{event.preventDefault();if(!clearing)setShowClear(false)}}><form onSubmit={clearRows}><div className="cost-pin-head"><Trash2 size={24}/><button type="button" className="cost-delete" aria-label="Löschfenster schließen" disabled={clearing} onClick={()=>setShowClear(false)}><X size={20}/></button></div><h2 id="cost-clear-title">Alle Zeilen löschen?</h2><label className="cost-month">Was soll gelöscht werden?<select aria-label="Löschumfang" value={clearScope} disabled={clearing} onChange={event=>setClearScope(event.target.value as "month"|"all")}><option value="month">Zusätzliche Monatsbuchungen ({month})</option><option value="all">Komplette Kostenrechnung</option></select></label><p>{clearScope==="all"?"Alle Monate, Gehalt, Fixkosten und Gegenrechnungen werden auf null zurückgesetzt.":`Alle zusätzlichen Buchungen in ${month} werden gelöscht. Fixe Einnahmen und Ausgaben bleiben erhalten.`}</p>{dirty&&clearScope==="month"&&<p>Deine übrigen Änderungen werden dabei mitgespeichert.</p>}<label htmlFor="cost-clear-pin">Zum Bestätigen PIN eingeben</label><input id="cost-clear-pin" aria-label="Lösch-PIN" autoFocus type="password" inputMode="numeric" autoComplete="off" pattern="[0-9]{4}" maxLength={4} value={clearPin} disabled={clearing} onChange={event=>setClearPin(event.target.value.replace(/\D/g,""))} required/>{clearError&&<p className="cost-error" role="alert">{clearError}</p>}<button className="button cost-clear-button" disabled={clearing||clearPin.length!==4}>{clearing?"Wird gelöscht …":"Mit PIN bestätigen und löschen"}</button><button type="button" className="button" disabled={clearing} onClick={()=>setShowClear(false)}>Abbrechen</button></form></dialog>
   {showImport&&<StatementImport plan={plan} token={token} onClose={()=>setShowImport(false)} onImport={(next,importMonth,count)=>{setPlan(next);if(importMonth)setMonth(importMonth);setTab("Monat");setDirty(true);setSaved("");setImported(`${count} Buchungen übernommen. Bitte speichern, damit sie auch auf anderen Geräten verfügbar sind.`);setShowImport(false)}}/>}
  </>}
 </div>
}
function Stat({label,value,balance=false}:{label:string;value:number;balance?:boolean}){return <div><small>{label}</small><b className={balance?(value<0?"cost-negative":"cost-positive"):""}>{euro(value)}</b></div>}
function Amount({value,onChange,label,disabled,signed=false}:{value:number;onChange:(amount:number)=>void;label:string;disabled:boolean;signed?:boolean}){
 const [text,setText]=useState(value.toFixed(2).replace(".",","));
 useEffect(()=>setText(value.toFixed(2).replace(".",",")),[value]);
 return <input aria-label={label} inputMode="decimal" disabled={disabled} value={text} onChange={event=>setText(event.target.value)} onBlur={()=>{const normalized=text.trim().replace(",",".");const parsed=Number(normalized);if(normalized!==""&&Number.isFinite(parsed)&&(signed||parsed>=0)&&Math.abs(parsed)<=1e9){const rounded=Math.round(parsed*100)/100;onChange(rounded);setText(rounded.toFixed(2).replace(".",","))}else setText(value.toFixed(2).replace(".",","))}} onKeyDown={event=>{if(event.key==="Enter")event.currentTarget.blur()}}/>
}
