"use client";
import { useEffect, useRef, useState } from "react";
import { FileUp, X } from "lucide-react";
import type { CostPlan } from "@/domain/cost-plan";
import { applyCostStatement, prepareCostStatement, fixedStatementChanges, type CostStatement, type StatementRow } from "@/domain/cost-statement";
import { readCostPdf } from "@/lib/cost-pdf";
const eur=(value:number)=>new Intl.NumberFormat("de-AT",{style:"currency",currency:"EUR"}).format(value);
export function StatementImport({plan,token,onClose,onImport}:{plan:CostPlan;token:string;onClose:()=>void;onImport:(plan:CostPlan,month:string,count:number)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);
 const [statement,setStatement]=useState<CostStatement|null>(null),[rows,setRows]=useState<StatementRow[]>([]),[filename,setFilename]=useState("");
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[replaceManual,setReplaceManual]=useState(false),[updateFixed,setUpdateFixed]=useState(false),[applyCurrent,setApplyCurrent]=useState(false),[acknowledged,setAcknowledged]=useState(false);
 useEffect(()=>{dialog.current?.showModal()},[]);
 async function selectFile(file?:File){
  if(!file)return;setBusy(true);setError("");setFilename(file.name);setStatement(null);setRows([]);setAcknowledged(false);
  try{const parsed=await readCostPdf(file,token);setStatement(parsed);setRows(prepareCostStatement(parsed.rows,plan,updateFixed))}catch(err){setError(err instanceof Error?err.message:"Die PDF konnte nicht gelesen werden.")}finally{setBusy(false)}
 }
 function patch(id:string,value:Partial<StatementRow>){setRows(current=>current.map(row=>row.id===id?{...row,...value}:row))}
 const selected=rows.filter(row=>row.selected),duplicates=rows.filter(row=>row.duplicate).length;
 const changes=updateFixed?fixedStatementChanges(plan,rows):[];
 const valid=selected.every(row=>row.name.trim()&&Number.isFinite(row.amount)&&row.amount>=0&&row.date);
 const total=(kind:"in"|"out")=>selected.filter(row=>row.kind===kind).reduce((sum,row)=>sum+row.amount,0);
 const months=new Set(selected.map(row=>row.date.slice(0,7)));
 const manualCount=plan.expenses.filter(row=>months.has(row.month)&&!row.sourceFingerprint).length;
 function accept(){try{const result=applyCostStatement(plan,rows,filename,{replaceManual,updateFixed,applyCurrent});onImport(result.plan,selected[0]?.date.slice(0,7)||"",result.count)}catch(err){setError(err instanceof Error?err.message:"Bitte die ausgewählten Buchungen prüfen.")}}
 return <dialog ref={dialog} className="cost-import-dialog" aria-labelledby="cost-import-title" onCancel={event=>{event.preventDefault();if(!busy)onClose()}}><header><div><small>KONTOAUSZUG</small><h2 id="cost-import-title">PDF importieren</h2></div><button className="cost-delete" aria-label="Import schließen" onClick={onClose} disabled={busy}><X size={18}/></button></header>
  <p className="cost-note">PDF auswählen, Buchungen prüfen und übernehmen. Du kannst Bezeichnungen und Zuordnung anpassen.</p>
  <label className="cost-pdf-file"><FileUp size={22}/><span>{busy?"Kontoauszug wird gelesen …":filename||"Sparkassen-Kontoauszug auswählen"}<small>PDF mit auswählbarem Text · maximal 20 MB</small></span><input aria-label="PDF-Kontoauszug" type="file" accept="application/pdf,.pdf" disabled={busy} onChange={event=>{void selectFile(event.target.files?.[0]);event.target.value=""}}/></label>
  <label className="cost-replace"><input type="checkbox" checked={updateFixed} disabled={busy} onChange={event=>{const enabled=event.target.checked;setUpdateFixed(enabled);if(statement)setRows(prepareCostStatement(rows,plan,enabled))}}/><span>Fixkosten aktualisieren<small>{updateFixed?"Änderungen unten prüfen: Fixkosten werden ergänzt, angepasst oder entfernt. Gehalt bleibt unverändert.":"Standard: Gehalt und Fixkosten bleiben unverändert. Passende Buchungen werden nicht doppelt importiert."}</small></span></label>
  {updateFixed&&<label className="cost-replace"><input type="checkbox" checked={applyCurrent} disabled={busy} onChange={event=>setApplyCurrent(event.target.checked)}/><span>Bei jetzigem Monat übernehmen<small>Ohne Haken gelten die Fixkosten-Änderungen ab dem nächsten Monat. Frühere Monate bleiben unverändert.</small></span></label>}
  {updateFixed&&months.size>1&&<p className="cost-error" role="alert">Fixkosten bitte mit einem Auszug für einen einzelnen Monat aktualisieren.</p>}
  {updateFixed&&statement&&<div className="cost-fixed-preview"><b>Änderungen an deinen Fixkosten</b>{changes.length?changes.map((change,index)=><p key={index}><strong>{change.action==="add"?"Neu":change.action==="remove"?"Entfernen":"Aktualisieren"}: {change.name}</strong> · {change.previous!==undefined&&eur(change.previous)+" → "}{eur(change.amount)}</p>):<p>Keine Änderungen.</p>}<small>Entfernen bedeutet: Dieser Fixposten fehlt unter den ausgewählten Fixkosten des Auszugs. Prüfe die Vorschau vor dem Übernehmen.</small></div>}
  {error&&<p className="cost-error" role="alert">{error}</p>}
  {statement&&<><div className="cost-import-summary"><div><small>Ausgewählte Buchungen</small><b>{selected.length} von {rows.length}</b></div><div><small>Einnahmen</small><b>{eur(total("in"))}</b></div><div><small>Ausgaben</small><b>{eur(total("out"))}</b></div></div>
   <div className="cost-import-controls">{statement.closing!==undefined&&<span>Kontostand laut PDF: <b>{eur(statement.closing)}</b></span>}{duplicates>0&&<span>{duplicates} bereits importiert</span>}<button className="button" onClick={()=>setRows(current=>current.map(row=>({...row,selected:!row.duplicate&&!current.some(item=>item.selected)})))}>{selected.length?"Alle abwählen":"Alle auswählen"}</button></div>
   {statement.warnings.length>0&&<div className="cost-error" role="alert">{statement.warnings.map(warning=><p key={warning}>{warning}</p>)}{rows.length>0&&<label><input type="checkbox" checked={acknowledged} onChange={event=>setAcknowledged(event.target.checked)}/>Ich habe die Buchungen mit dem Auszug geprüft.</label>}</div>}
   <div className="cost-import-list">{rows.map(row=><article key={row.id} className={`cost-import-row ${row.duplicate?"is-duplicate":""}`}><label className="cost-import-check"><input type="checkbox" aria-label={"Übernehmen "+row.name} checked={row.selected} disabled={row.duplicate&&!(updateFixed&&row.target==="monthlyFixed")} onChange={event=>patch(row.id,{selected:event.target.checked,keepMonthly:event.target.checked&&Boolean(row.matchedRegular)&&!updateFixed})}/><span>{row.matchedRegular?"Bereits geplant: "+row.matchedRegular:row.duplicate?"Bereits importiert":row.kind==="in"?"Geld rein":"Geld raus"}</span></label><div className="cost-import-fields"><label>Datum<input type="date" value={row.date} onChange={event=>patch(row.id,{date:event.target.value})}/></label><label>Bezeichnung<input value={row.name} maxLength={300} onChange={event=>patch(row.id,{name:event.target.value})}/></label><label>Betrag €<input type="number" inputMode="decimal" min="0" step="0.01" value={row.amount} onChange={event=>patch(row.id,{amount:event.target.value===""?NaN:Number(event.target.value)})}/></label><label>Zuordnung<select value={row.target} onChange={event=>patch(row.id,{target:event.target.value as StatementRow["target"]})}><option value="expenses">{row.kind==="in"?"Monatseinnahme":"Monatsausgabe"}</option>{updateFixed&&row.kind==="out"&&<option value="monthlyFixed">Fixkosten aktualisieren</option>}</select></label></div><details><summary>Buchungstext anzeigen</summary><p>{row.note}</p></details></article>)}</div>
   {manualCount>0&&<label className="cost-replace"><input type="checkbox" checked={replaceManual} onChange={event=>setReplaceManual(event.target.checked)}/><span>{manualCount} vorhandene Monatsausgaben ohne PDF-Quelle ersetzen<small>Andere Monate und die allgemeinen Fixkosten bleiben erhalten.</small></span></label>}
  </>}
  <footer><button className="button" disabled={busy} onClick={onClose}>Abbrechen</button><button className="button primary" disabled={busy||(!selected.length&&!changes.length)||!valid||(updateFixed&&months.size>1)||Boolean(statement?.warnings.length&&!acknowledged)} onClick={accept}>{selected.length} Buchungen{updateFixed?" & Fixkosten":""} übernehmen</button></footer>
 </dialog>
}
