export type ImportDraft={id:string;title:string;amount:string;kind:"in"|"out";recipient:string;method:string;date:string;sourceRow:number;duplicate:boolean};

const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("de").replace(/[^a-z0-9]+/g," ").trim();
const candidates={date:["buchungstag","buchungsdatum","datum","buchungs tag"],title:["verwendungszweck","buchungstext","umsatzart","zweck","buchung"],recipient:["begunstigter zahlungspflichtiger","begunstigter zahlungspflichtiger name","zahlungspflichtiger","begunstigter","empfaenger","auftraggeber","name gegenkonto","partnername","payee"],amount:["betrag","umsatz","betrag eur","umsatz eur"],debit:["soll","belastung","lastschrift"],credit:["haben","gutschrift","einnahme"]};
function splitCsv(text:string,delimiter:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===delimiter&&!quoted){row.push(cell.trim());cell=""}else if((ch==="\n"||ch==="\r")&&!quoted){if(ch==="\r"&&text[i+1]==="\n")i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=""}else cell+=ch}row.push(cell.trim());if(row.some(Boolean))rows.push(row);return rows}
function chooseDelimiter(text:string){const first=text.replace(/^\uFEFF/,"").split(/\r?\n/,1)[0]||"";return [";",",","\t"].map(delimiter=>({delimiter,count:(first.match(new RegExp(delimiter==="\t"?"\\t":`\\${delimiter}`,"g"))||[]).length})).sort((a,b)=>b.count-a.count)[0]?.delimiter||";"}
const col=(headers:string[],options:string[])=>headers.findIndex(header=>options.includes(header)||options.some(option=>header.startsWith(option+" ")));
const amountValue=(raw:string)=>{let value=raw.replace(/[€\s]/g,"").replace(/[−–]/g,"-");if(value.includes(",")){value=value.replace(/\./g,"").replace(",",".")}else if((value.match(/\./g)||[]).length>1){const pieces=value.split(".");value=pieces.slice(0,-1).join("")+"."+pieces.at(-1)}const parsed=Number(value);return Number.isFinite(parsed)?parsed:null};
const dateValue=(raw:string)=>{const value=raw.trim();let match=value.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})$/);if(match)return `${match[1].padStart(2,"0")}.${match[2].padStart(2,"0")}.${match[3]}`;match=value.match(/^(\d{4})-(\d{2})-(\d{2})/);if(match)return `${match[3]}.${match[2]}.${match[1]}`;return ""};
const guessMethod=(text:string)=>{const v=text.toLocaleLowerCase("de");return /karte|card|visa|mastercard|pos/.test(v)?"Karte":/lastschrift|sepa dd/.test(v)?"Lastschrift":/bar|atm/.test(v)?"Bar":/uberweis|sepa|standing order/.test(v)?"Überweisung":"Sonstiges"};
export function parseStatementCsv(text:string):ImportDraft[]{const rows=splitCsv(text,chooseDelimiter(text));if(rows.length<2)return[];let headerAt=0;for(let i=0;i<Math.min(rows.length,8);i++){if(rows[i].length>2&&rows[i].some(cell=>/buchung|datum|verwendung|betrag|umsatz|soll|haben/i.test(cell))){headerAt=i;break}}const headers=rows[headerAt].map(normalize);const indexes={date:col(headers,candidates.date),title:col(headers,candidates.title),recipient:col(headers,candidates.recipient),amount:col(headers,candidates.amount),debit:col(headers,candidates.debit),credit:col(headers,candidates.credit)};const read=(row:string[],index:number)=>index<0?"":row[index]||"";const records:ImportDraft[]=[];for(let i=headerAt+1;i<rows.length;i++){const row=rows[i];if(!row.some(Boolean))continue;const rawTitle=read(row,indexes.title);const rawDate=read(row,indexes.date);let value=indexes.amount>=0?amountValue(read(row,indexes.amount)):null;let kind:"in"|"out"="out";if(indexes.debit>=0||indexes.credit>=0){const debit=amountValue(read(row,indexes.debit));const credit=amountValue(read(row,indexes.credit));if(credit!==null&&credit!==0){kind="in";value=Math.abs(credit)}else if(debit!==null&&debit!==0){kind="out";value=Math.abs(debit)}}else if(value!==null&&value<0){kind="out";value=Math.abs(value)}else if(value!==null&&value>0){kind="in"}const detail=read(row,headers.findIndex(h=>/umsatztyp|zahlungsart|art der buchung/.test(h)));records.push({id:`row-${i}-${Math.random().toString(36).slice(2,7)}`,title:rawTitle.trim(),amount:value===null?"":value.toFixed(2).replace(".",","),kind,recipient:read(row,indexes.recipient).trim(),method:guessMethod(`${rawTitle} ${detail}`),date:dateValue(rawDate),sourceRow:i+1,duplicate:false})}return records}
export async function decodeStatementFile(file:File){const buffer=await file.arrayBuffer();const bytes=new Uint8Array(buffer);let text:string;if(bytes[0]===0xff&&bytes[1]===0xfe)text=new TextDecoder("utf-16le").decode(bytes.subarray(2));else if(bytes[0]===0xfe&&bytes[1]===0xff)text=new TextDecoder("utf-16be").decode(bytes.subarray(2));else{text=new TextDecoder("utf-8").decode(buffer);if(text.includes("\uFFFD"))text=new TextDecoder("windows-1252").decode(buffer)}return text.replace(/^\uFEFF/,"")}
export function markDuplicateDrafts(rows:ImportDraft[]){const seen=new Set<string>();return rows.map(row=>{const key=[row.kind,row.date,row.amount,normalize(row.title),normalize(row.recipient)].join("|");const duplicate=seen.has(key);if(key.replaceAll("|","").trim())seen.add(key);return{...row,duplicate}})}
