// Increase this whenever stored provider recipes need to be checked again.
export const RECIPE_POLICY_VERSION = 1;
type RecipeText = {name:string;category?:string;description?:string;instructions?:string[];ingredients?:{name:string;hint?:string;amount?:string}[]};
const seafood = /\b(?:fish\w*|seafood|shellfish|salmon|tuna|anchov\w*|sardine\w*|mackerel|herring|haddock|cod|trout|tilapia|halibut|pollock|hake|sole|monkfish|sea\s*bass|sea\s*bream|shrimp\w*|prawn\w*|scampi|crab\w*|lobster\w*|crayfish|crawfish|mussel\w*|clam\w*|oyster\w*|scallop\w*|squid|octopus|calamari|cuttlefish|surimi|caviar|roe|dashi|bonito|katsuobushi|worcestershire|fisch\w*|meeresfr\w*|meerestiere|lachs\w*|thunfisch\w*|sardell\w*|sardine\w*|makrel\w*|hering\w*|kabeljau\w*|dorsch\w*|forell\w*|heilbutt\w*|scholle\w*|seelachs\w*|zander\w*|karpfen\w*|aal|garnel\w*|krabbe\w*|hummer\w*|languste\w*|krebs\w*|muschel\w*|auster\w*|tintenfisch\w*|kaviar\w*|dorade\w*|saibling\w*|wolfsbarsch\w*|barsch\w*|hecht\w*|seeteufel\w*|pangasius\w*|steinbutt\w*|saumon|thon|anchois|crevette\w*|poisson\w*|fruits de mer|pesce|pescado|marisco\w*|gamber\w*|acciug\w*|tonno)\b/iu;
export function containsSeafood(recipe:RecipeText){
  return seafood.test([recipe.name,recipe.category,recipe.description,...(recipe.instructions??[]),...(recipe.ingredients??[]).flatMap(item=>[item.name,item.hint,item.amount])].filter(Boolean).join(" ").normalize("NFD").replace(/[\u0300-\u036f]/g,""));
}
// Catch untranslated culinary words even in sources labelled German.
export function hasEnglishRecipeWords(text:string){return /\b(?:the|with|into|until|then|add|stir|heat|cook|bake|preheat|serve|mix|chop|slice|drain|remove|place|pour|sprinkle|combine|bring|allow|minutes|tablespoons?|teaspoons?|cups?|chopped|diced|grated|crushed|peeled|finely|fresh|dried|ground|chicken|beef|pork|onions?|garlic|potatoes?|tomatoes?|flour|sugar|salt|pepper|cheese|cream|milk|eggs?|oil|parsley|coriander|cinnamon|bowl|pan|oven|saucepan|water|stock|broth|breadcrumbs|breakfast|vegetarian|vegan recipes|american|british|italian|red|green|yellow|black|white|sweet|sour|cabbage|lettuce|peas|beans|chickpeas|lentils|coconut|lemon|lime|apple|banana|mushrooms?|broccoli|spinach|oats|honey|syrup|noodles?|almonds?|walnuts?|basil|thyme|rosemary|cumin|nutmeg|vanilla|yeast|baking|mustard|vinegar|delicious|tasty|recipe|easy|quick|homemade|garnish|taste|optional|sprigs?|bunch|handful|medium|large|small)\b/i.test(text)}
