import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import path from "node:path";

export type HouseholdState=Record<string,unknown>;
const stateFile=()=>path.join(process.env.WG_DATA_DIR||path.join(process.cwd(),".data"),"household.json");
let queue:Promise<unknown>=Promise.resolve();
export async function readHousehold():Promise<HouseholdState>{try{return JSON.parse(await readFile(stateFile(),"utf8")) as HouseholdState}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return{};throw error}}
export async function updateHousehold(key:string,value:unknown){const work=queue.then(async()=>{const file=stateFile();await mkdir(path.dirname(file),{recursive:true});const state=await readHousehold();state[key]=value;const temp=`${file}.${Date.now()}.tmp`;await writeFile(temp,JSON.stringify(state),"utf8");await rename(temp,file);return state});queue=work.then(()=>undefined,()=>undefined);return work}
export async function createHouseholdBooking(entry:{id:number;kind:"in"|"out";title:string;amount:number;recipient:string;method:string;date:string;detail?:string}){const work=queue.then(async()=>{const file=stateFile();await mkdir(path.dirname(file),{recursive:true});const state=await readHousehold();const bookings=Array.isArray(state.bookings)?state.bookings as typeof entry[]:[];bookings.unshift(entry);state.bookings=bookings;const current=typeof state.accountBalance==="number"?state.accountBalance:1842.54;state.accountBalance=Math.round((current+(entry.kind==="in"?entry.amount:-entry.amount))*100)/100;const temp=`${file}.${Date.now()}.tmp`;await writeFile(temp,JSON.stringify(state),"utf8");await rename(temp,file);return{state,entry,accountBalance:state.accountBalance as number}});queue=work.then(()=>undefined,()=>undefined);return work}
type ImportedBooking={id:number;kind:"in"|"out";title:string;amount:number;recipient:string;method:string;date:string;detail?:string;importFingerprint:string};
const fingerprint=(entry:Pick<ImportedBooking,"kind"|"title"|"amount"|"recipient"|"date">)=>[entry.kind,entry.date,entry.amount.toFixed(2),entry.title,entry.recipient].map(value=>String(value).normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().replace(/\s+/g," ").toLocaleLowerCase("de")).join("|");
export async function importHouseholdBookings(entries:ImportedBooking[]){const work=queue.then(async()=>{const file=stateFile();await mkdir(path.dirname(file),{recursive:true});const state=await readHousehold();const bookings=Array.isArray(state.bookings)?state.bookings as (ImportedBooking&Record<string,unknown>)[]:[];const known=new Set(bookings.map(entry=>typeof entry.importFingerprint==="string"?entry.importFingerprint:fingerprint(entry)));const accepted:ImportedBooking[]=[];let skipped=0;for(const entry of entries){const key=fingerprint(entry);if(known.has(key)){skipped++;continue}known.add(key);accepted.push({...entry,importFingerprint:key})}bookings.unshift(...accepted);state.bookings=bookings;const temp=`${file}.${Date.now()}.tmp`;await writeFile(temp,JSON.stringify(state),"utf8");await rename(temp,file);return{entries:accepted,imported:accepted.length,skipped}});queue=work.then(()=>undefined,()=>undefined);return work}
