import {mkdir,readFile,rename,writeFile} from "node:fs/promises";
import path from "node:path";

export type HouseholdState=Record<string,unknown>;
const stateFile=()=>path.join(process.env.WG_DATA_DIR||path.join(process.cwd(),".data"),"household.json");
let queue:Promise<unknown>=Promise.resolve();
export async function readHousehold():Promise<HouseholdState>{try{return JSON.parse(await readFile(stateFile(),"utf8")) as HouseholdState}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return{};throw error}}
function same(a:unknown,b:unknown){return JSON.stringify(a)===JSON.stringify(b)}
function mergeConcurrentValue(base:unknown,current:unknown,incoming:unknown):unknown{
 if(Array.isArray(base)&&Array.isArray(current)&&Array.isArray(incoming)){
  const primitive=base.every(x=>x===null||typeof x!=="object")&&current.every(x=>x===null||typeof x!=="object")&&incoming.every(x=>x===null||typeof x!=="object");
  if(primitive){const identity=(x:unknown)=>JSON.stringify(x);const baseSet=new Set(base.map(identity));const incomingSet=new Set(incoming.map(identity));const removed=new Set(base.filter(x=>!incomingSet.has(identity(x))).map(identity));const result=current.filter(x=>!removed.has(identity(x)));const resultSet=new Set(result.map(identity));for(const item of incoming)if(!baseSet.has(identity(item))&&!resultSet.has(identity(item))){result.push(item);resultSet.add(identity(item))}return [...incoming.filter(x=>resultSet.has(identity(x))),...result.filter(x=>!incomingSet.has(identity(x)))]}
  const hasIds=[base,current,incoming].every(list=>list.every(row=>row&&typeof row==="object"&&"id" in row));if(!hasIds)return incoming;
  const id=(row:unknown)=>String((row as {id:unknown}).id);const baseMap=new Map(base.map(row=>[id(row),row as Record<string,unknown>]));const currentMap=new Map(current.map(row=>[id(row),row as Record<string,unknown>]));const incomingMap=new Map(incoming.map(row=>[id(row),row as Record<string,unknown>]));
  for(const [key] of baseMap)if(!incomingMap.has(key))currentMap.delete(key);
  for(const [key,row] of incomingMap){const before=baseMap.get(key);const now=currentMap.get(key);if(!before){if(!now)currentMap.set(key,row);continue}if(!now)continue;const merged={...now};for(const field of new Set([...Object.keys(before),...Object.keys(row)])){if(!same(before[field],row[field])){if(Object.prototype.hasOwnProperty.call(row,field))merged[field]=row[field];else delete merged[field]}}currentMap.set(key,merged)}
  const order=[...incoming.map(id),...current.map(id).filter(key=>!incomingMap.has(key))];return [...new Set(order)].map(key=>currentMap.get(key)).filter((row):row is Record<string,unknown>=>Boolean(row));
 }
 if(base&&current&&incoming&&typeof base==="object"&&typeof current==="object"&&typeof incoming==="object"&&!Array.isArray(base)&&!Array.isArray(current)&&!Array.isArray(incoming)){const before=base as Record<string,unknown>;const now=current as Record<string,unknown>;const next=incoming as Record<string,unknown>;const merged={...now};for(const field of new Set([...Object.keys(before),...Object.keys(next)])){if(!same(before[field],next[field])){if(Object.prototype.hasOwnProperty.call(next,field))merged[field]=next[field];else delete merged[field]}}return merged}
 return same(base,incoming)?current:incoming;
}
export async function updateHousehold(key:string,value:unknown,baseValue?:unknown){const work=queue.then(async()=>{const file=stateFile();await mkdir(path.dirname(file),{recursive:true});const state=await readHousehold();state[key]=baseValue===undefined?value:mergeConcurrentValue(baseValue,state[key],value);const temp=`${file}.${Date.now()}.tmp`;await writeFile(temp,JSON.stringify(state),"utf8");await rename(temp,file);return state});queue=work.then(()=>undefined,()=>undefined);return work}
export async function createHouseholdBooking(entry:{id:number;kind:"in"|"out";title:string;amount:number;recipient:string;method:string;date:string;detail?:string}){const work=queue.then(async()=>{const file=stateFile();await mkdir(path.dirname(file),{recursive:true});const state=await readHousehold();const bookings=Array.isArray(state.bookings)?state.bookings as typeof entry[]:[];bookings.unshift(entry);state.bookings=bookings;const current=typeof state.accountBalance==="number"?state.accountBalance:1842.54;state.accountBalance=Math.round((current+(entry.kind==="in"?entry.amount:-entry.amount))*100)/100;const temp=`${file}.${Date.now()}.tmp`;await writeFile(temp,JSON.stringify(state),"utf8");await rename(temp,file);return{state,entry,accountBalance:state.accountBalance as number}});queue=work.then(()=>undefined,()=>undefined);return work}
type ImportedBooking={id:number;kind:"in"|"out";title:string;amount:number;recipient:string;method:string;date:string;detail?:string;importFingerprint:string};
const fingerprint=(entry:Pick<ImportedBooking,"kind"|"title"|"amount"|"recipient"|"date">)=>[entry.kind,entry.date,entry.amount.toFixed(2),entry.title,entry.recipient].map(value=>String(value).normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().replace(/\s+/g," ").toLocaleLowerCase("de")).join("|");
export async function importHouseholdBookings(entries:ImportedBooking[]){const work=queue.then(async()=>{const file=stateFile();await mkdir(path.dirname(file),{recursive:true});const state=await readHousehold();const bookings=Array.isArray(state.bookings)?state.bookings as (ImportedBooking&Record<string,unknown>)[]:[];const known=new Set(bookings.map(entry=>typeof entry.importFingerprint==="string"?entry.importFingerprint:fingerprint(entry)));const accepted:ImportedBooking[]=[];let skipped=0;for(const entry of entries){const key=fingerprint(entry);if(known.has(key)){skipped++;continue}known.add(key);accepted.push({...entry,importFingerprint:key})}bookings.unshift(...accepted);state.bookings=bookings;const temp=`${file}.${Date.now()}.tmp`;await writeFile(temp,JSON.stringify(state),"utf8");await rename(temp,file);return{entries:accepted,imported:accepted.length,skipped}});queue=work.then(()=>undefined,()=>undefined);return work}
