import {readFile} from "node:fs/promises";

export type Health="healthy"|"warning"|"offline";
export type ServiceStatus={name:string;status:Health;cpu:string;ram:string;uptime:string;restartCount:number;version?:string;updateAvailable?:boolean};
export type ResourceSnapshot={cpuPercent:number;memoryPercent:number;storagePercent:number;host:string;processor:string;os:string};
export type SensorSnapshot={entityId:string;name:string;state:string;unit?:string;deviceClass?:string};
export type MonitorSnapshot={systems:string;docker:string;homeAssistant:string;responseTime:string;nasStorage:string;services:ServiceStatus[];sensors:SensorSnapshot[];portainerConfigured:boolean;resources:ResourceSnapshot;warnings:{title:string;detail:string}[];source:"Home Assistant live"|"Demo";network:string;updatedAt:string};
export interface MonitorProvider{getSnapshot(options?:{force?:boolean}):Promise<MonitorSnapshot>}
const pct=(value:number|undefined)=>Number.isFinite(value)?Math.max(0,Math.min(100,Math.round(value!))):0;
const fmtBytes=(bytes:number|undefined)=>Number.isFinite(bytes)?`${Math.round(bytes!/1024/1024)} MB`:"–";
async function supervisor<T>(endpoint:string,timeout=3000,method:"GET"|"POST"="GET"):Promise<T>{const token=process.env.SUPERVISOR_TOKEN;if(!token)throw new Error("Supervisor API ist nicht verfügbar.");const response=await fetch(`http://supervisor/${endpoint}`,{method,headers:{Authorization:`Bearer ${token}`,Accept:"application/json",...(method==="POST"?{"Content-Type":"application/json"}:{})},...(method==="POST"?{body:"{}"}:{}),cache:"no-store",signal:AbortSignal.timeout(timeout)});if(!response.ok)throw new Error(`Supervisor ${endpoint}: ${response.status}`);const body=await response.json().catch(()=>({}));return(body?.data??body) as T;}
export async function refreshCockpitRepository(){
 const result=await supervisor<Array<{slug?:string;url?:string;source?:string}>|{repositories?:Array<{slug?:string;url?:string;source?:string}>}>("store/repositories");
 const repositories=Array.isArray(result)?result:result.repositories??[];
 const canonical=(value:string)=>value.trim().replace(/\.git$/i,"").replace(/\/$/,"").toLocaleLowerCase("en-US");
 const target=canonical("https://github.com/firebreakHD/WHBoard");
 const repository=repositories.find(item=>[item.url,item.source].some(value=>typeof value==="string"&&canonical(value)===target));
 if(!repository?.slug)throw new Error("Das private WHBoard-Repository wurde in Home Assistant nicht gefunden.");
 await supervisor(`store/repositories/${encodeURIComponent(repository.slug)}/repair`,15000,"POST");
 await supervisor("store/reload",10000,"POST");
 return{repository:repository.slug};
}
async function portainerConfig(){let options:{portainer_url?:string;portainer_api_key?:string}={};try{options=JSON.parse(await readFile("/data/options.json","utf8")) as typeof options}catch{}const url=process.env.PORTAINER_URL||options.portainer_url||"";const apiKey=process.env.PORTAINER_API_KEY||options.portainer_api_key||"";return{url:url.replace(/\/$/,""),apiKey,configured:Boolean(url&&apiKey)}}
async function portainerContainers(){const config=await portainerConfig();if(!config.configured)return{containers:[] as ServiceStatus[],configured:false,error:false};try{const headers={"X-API-Key":config.apiKey,Accept:"application/json"};const endpointResponse=await fetch(`${config.url}/api/endpoints`,{headers,cache:"no-store",signal:AbortSignal.timeout(2500)});if(!endpointResponse.ok)throw new Error("Portainer API nicht erreichbar");const endpoints=await endpointResponse.json() as PortainerEndpoint[];const results=await Promise.allSettled(endpoints.map(async endpoint=>{const response=await fetch(`${config.url}/api/endpoints/${encodeURIComponent(String(endpoint.Id))}/docker/containers/json?all=true`,{headers,cache:"no-store",signal:AbortSignal.timeout(3000)});if(!response.ok)throw new Error("Docker-Abfrage fehlgeschlagen");const containers=await response.json() as PortainerContainer[];return containers.map(container=>{const name=(container.Names?.[0]||container.Id).replace(/^\//,"");const running=container.State==="running";return{name:`${name} · ${endpoint.Name}`,status:running?"healthy":container.State==="exited"?"offline":"warning",cpu:"–",ram:"–",uptime:container.Status||container.State,restartCount:container.RestartCount||0,version:container.Image} as ServiceStatus})}));return{containers:results.flatMap(x=>x.status==="fulfilled"?x.value:[]),configured:true,error:results.some(x=>x.status==="rejected")}}catch{return{containers:[] as ServiceStatus[],configured:true,error:true}}}

export class HomeAssistantMonitorProvider implements MonitorProvider{
 async getSnapshot():Promise<MonitorSnapshot>{
  const started=Date.now();
  const [addonsResult,hostResult,coreResult,coreStatsResult,supervisorResult,networkResult,sensorsResult,portainerResult]=await Promise.allSettled([
   supervisor<{addons?:Addon[]}>("addons"),supervisor<HostInfo>("host/info"),supervisor<CoreInfo>("core/info"),supervisor<Stats>("core/stats"),supervisor<SupervisorInfo>("supervisor/info"),supervisor<NetworkInfo>("network/info"),supervisor<CoreState[]>("core/api/states"),portainerContainers()
  ]);
  if(addonsResult.status!=="fulfilled"&&hostResult.status!=="fulfilled"&&coreResult.status!=="fulfilled")throw new Error("Home Assistant Supervisor nicht erreichbar");
  const addons=addonsResult.status==="fulfilled"?(addonsResult.value.addons??[]):[];const host=hostResult.status==="fulfilled"?hostResult.value:{};const core=coreResult.status==="fulfilled"?coreResult.value:{};const coreStats=coreStatsResult.status==="fulfilled"?coreStatsResult.value:{};const supervisorInfo=supervisorResult.status==="fulfilled"?supervisorResult.value:{};const net=networkResult.status==="fulfilled"?networkResult.value:{};
  const installed=addons.filter(a=>a.installed!==false);const addonStats=await Promise.all(installed.slice(0,32).map(async addon=>{try{return[addon.slug,await supervisor<Stats>(`addons/${encodeURIComponent(addon.slug)}/stats`,1500)] as const}catch{return[addon.slug,null] as const}}));const statsBySlug=new Map(addonStats);
  const services:ServiceStatus[]=[{name:"Home Assistant Core",status:"healthy",cpu:`${pct(coreStats.cpu_percent)} %`,ram:fmtBytes(coreStats.memory_usage),uptime:"Online",restartCount:0,version:core.version,updateAvailable:core.update_available},...installed.map(a=>{const stats=statsBySlug.get(a.slug)??null;const up=a.state==="started";return{name:a.name,status:up?(a.update_available?"warning":"healthy"):"offline",cpu:stats?`${pct(stats.cpu_percent)} %`:"–",ram:stats?fmtBytes(stats.memory_usage):"–",uptime:up?"Aktiv":"Gestoppt",restartCount:0,version:a.version??undefined,updateAvailable:a.update_available} as ServiceStatus})];
  const portainer=portainerResult.status==="fulfilled"?portainerResult.value:{containers:[] as ServiceStatus[],configured:false,error:false};services.push(...portainer.containers);
  const total=Number(host.disk_total??0),used=Number(host.disk_used??0),connected=net.host_internet!==false;const warnings:{title:string;detail:string}[]=[];
  if(supervisorResult.status==="fulfilled"&&supervisorInfo.healthy===false)warnings.push({title:"Supervisor meldet Probleme",detail:"Bitte Home Assistant Systemmeldungen prüfen."});
  for(const a of installed.filter(x=>x.update_available))warnings.push({title:`Update verfügbar: ${a.name}`,detail:`Installiert ${a.version??"unbekannt"} · verfügbar ${a.version_latest??"neuere Version"}`});
  if(core.update_available)warnings.push({title:"Home Assistant Core Update verfügbar",detail:`Installiert ${core.version??"?"} · verfügbar ${core.version_latest??"neue Version"}`});
  if(!connected)warnings.push({title:"Host ohne Internetverbindung",detail:"Home Assistant meldet keine aktive Internetverbindung."});
  if(portainer.error)warnings.push({title:"Portainer nicht erreichbar",detail:"Prüfe URL und API-Zugang in den Admin Cockpit Add-on-Einstellungen."});
  const sensors=sensorsResult.status==="fulfilled"?sensorsResult.value.filter(x=>x.entity_id?.startsWith("sensor.")||x.entity_id?.startsWith("binary_sensor.")).map(x=>({entityId:x.entity_id,name:String(x.attributes?.friendly_name??x.entity_id),state:String(x.state),unit:typeof x.attributes?.unit_of_measurement==="string"?x.attributes.unit_of_measurement:undefined,deviceClass:typeof x.attributes?.device_class==="string"?x.attributes.device_class:undefined})).sort((a,b)=>a.name.localeCompare(b.name,"de")):[];
  const online=services.filter(s=>s.status!=="offline").length;const interfaces=net.interfaces??[];const primary=interfaces.find((i:NetworkInterfaceInfo)=>i.primary)||interfaces[0];
  return{systems:`${online} / ${services.length}`,docker:`${installed.length+portainer.containers.length} Apps & Container`,homeAssistant:core.version?`Online · ${core.version}`:"Online",responseTime:`${Date.now()-started} ms`,nasStorage:total?`${Math.round(used/total*100)} % belegt`:"Nicht gemeldet",services,sensors,portainerConfigured:portainer.configured,resources:{cpuPercent:pct(coreStats.cpu_percent),memoryPercent:pct(coreStats.memory_percent),storagePercent:total?pct(used/total*100):0,host:host.hostname||"Home Assistant Host",processor:host.chassis||"Supervisor Hardware",os:host.operating_system||"Home Assistant OS"},warnings,source:"Home Assistant live",network:primary?`${primary.interface} · ${primary.type}${primary.ipv4?.ip_address?` · ${primary.ipv4.ip_address}`:""}`:connected?"Verbunden":"Offline",updatedAt:new Date().toISOString()};
 }
}
export class DemoMonitorProvider implements MonitorProvider{async getSnapshot():Promise<MonitorSnapshot>{return{systems:"Demo",docker:"Demo",homeAssistant:"Nicht verbunden",responseTime:"–",nasStorage:"–",services:[],sensors:[],portainerConfigured:false,resources:{cpuPercent:0,memoryPercent:0,storagePercent:0,host:"Home Assistant noch nicht verbunden",processor:"–",os:"–"},warnings:[{title:"Live-Daten erscheinen in Home Assistant",detail:"Starte dieses Portal als Home Assistant App mit Supervisor-API-Berechtigung."}],source:"Demo",network:"Nicht verbunden",updatedAt:new Date().toISOString()}}}
type Addon={slug:string;name:string;installed?:boolean;state?:string;version?:string|null;version_latest?:string|null;update_available?:boolean};type Stats={cpu_percent?:number;memory_usage?:number;memory_percent?:number};type HostInfo={hostname?:string;chassis?:string;operating_system?:string;disk_total?:number;disk_used?:number};type CoreInfo={version?:string;version_latest?:string;update_available?:boolean};type SupervisorInfo={healthy?:boolean};type NetworkInterfaceInfo={interface:string;type:string;primary?:boolean;ipv4?:{ip_address?:string}};type NetworkInfo={host_internet?:boolean;interfaces?:NetworkInterfaceInfo[]};type CoreState={entity_id:string;state:string;attributes?:Record<string,unknown>};type PortainerEndpoint={Id:number;Name:string};type PortainerContainer={Id:string;Names?:string[];State:string;Status:string;Image:string;RestartCount?:number};
const sourceProvider:MonitorProvider=process.env.SUPERVISOR_TOKEN?new HomeAssistantMonitorProvider():new DemoMonitorProvider();let cachedSnapshot:Promise<MonitorSnapshot>|null=null;let cachedAt=0;
export const monitorProvider:MonitorProvider={getSnapshot({force=false}={}){if(!force&&cachedSnapshot&&Date.now()-cachedAt<20000)return cachedSnapshot;cachedAt=Date.now();cachedSnapshot=sourceProvider.getSnapshot();cachedSnapshot.catch(()=>{cachedSnapshot=null});return cachedSnapshot}};
